#
# copy/paste of MS950.b2c-irreversible
#
# removed the entries of MS950.c2b-irreversible etries, this .nr
# table only includes "b->c only" entries
# (we don't need a MS950.c2b, the entries of MS950.c2b-irreversible
#  are added in MS950.b2c already)
#
0xF9FA  0x256D 
0xF9FB  0x256E
0xF9FC  0x2570
0xF9FD  0x256F
0xA2CC  0x5341
0xA2CE  0x5345
0xF9F9  0x2550
0xF9E9  0x255E
0xF9EA  0x256A
0xF9EB  0x2561
