/*
 * Copyright (c) 1997, 2011, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

/*
 * (C) Copyright Taligent, Inc. 1996, 1997 - All Rights Reserved
 * (C) Copyright IBM Corp. 1996 - 1998 - All Rights Reserved
 *
 * The original version of this source code and documentation
 * is copyrighted and owned by Taligent, Inc., a wholly-owned
 * subsidiary of IBM. These materials are provided under terms
 * of a License Agreement between Taligent and Sun. This technology
 * is protected by multiple US and International patents.
 *
 * This notice and attribution to Taligent may not be removed.
 * Taligent is a registered trademark of Taligent, Inc.
 *
 */

package sun.util.resources;

public final class TimeZoneNames_fr extends TimeZoneNamesBundle {

    protected final Object[][] getContents() {
        String ACT[] = new String[] {"Heure de l'Acre", "ACT",
                                     "Heure d'\u00e9t\u00e9 de l'Acre", "ACST"};
        String ADELAIDE[] = new String[] {"Heure standard d'Australie centrale (Australie du sud)", "CST",
                                          "Heure d'\u00e9t\u00e9 d'Australie centrale (Australie du sud)", "CST"};
        String AGT[] = new String[] {"Heure D'Argentine", "ART",
                                     "Heure d'\u00e9t\u00e9 D'Argentine", "ARST"} ;
        String AKST[] = new String[] {"Heure normale d'Alaska", "AKST",
                                      "Heure avanc\u00e9e d'Alaska", "AKDT"} ;
        String AMT[] = new String[] {"Heure normale d'Amazonie", "AMT",
                                     "Heure d'\u00e9t\u00e9 d'Amazonie", "AMST"} ;
        String ARAST[] = new String[] {"Heure normale d'Arabie", "AST",
                                       "Heure avanc\u00e9e d'Arabie", "ADT"} ;
        String ARMT[] = new String[] {"Heure d'Arm\u00e9nie", "AMT",
                                      "Heure d'\u00e9t\u00e9 d'Arm\u00e9nie", "AMST"} ;
        String AST[] = new String[] {"Heure normale de l'Atlantique", "AST",
                                     "Heure avanc\u00e9e de l'Atlantique", "ADT"} ;
        String BDT[] = new String[] {"Heure du Bangladesh", "BDT",
                                     "Heure d'\u00e9t\u00e9 du Bangladesh", "BDST"} ;
        String BRISBANE[] = new String[] {"Heure standard d'Australie orientale (Queensland)", "EST",
                                          "Heure d'\u00e9t\u00e9 d'Australie orientale (Queensland)", "EST"};
        String BROKEN_HILL[] = new String[] {"Heure standard d'Australie centrale (Australie du sud/Nouvelle-Galles du sud)", "CST",
                                             "Heure d'\u00e9t\u00e9 d'Australie centrale(Australie du sud/Nouvelle-Galles du sud)", "CST"};
        String BRT[] = new String[] {"Heure du Br\u00e9sil", "BRT",
                                     "Heure d'\u00e9t\u00e9 du Br\u00e9sil", "BRST"} ;
        String BTT[] = new String[] {"Heure du Bhoutan", "BTT",
                                     "Heure d'\u00e9t\u00e9 du Bhoutan", "BTST"} ;
        String CAT[] = new String[] {"Heure d'Afrique centrale", "CAT",
                                     "Heure d'\u00e9t\u00e9 d'Afrique centrale", "CAST"} ;
        String CET[] = new String[] {"Heure d'Europe centrale", "CET",
                                     "Heure d'\u00e9t\u00e9 d'Europe centrale", "CEST"} ;
        String CHAST[] = new String[] {"Heure standard de Chatham", "CHAST",
                                       "Heure avanc\u00e9e de Chatham", "CHADT"};
        String CHUT[] = new String[] {"Chuuk Time", "CHUT",
                                      "Chuuk Summer Time", "CHUST"};
        String CIT[] = new String[] {"Heure d'Indon\u00e9sie centrale", "CIT",
                                     "Heure d'\u00e9t\u00e9 d'Indon\u00e9sie centrale", "CIST"};
        String CLT[] = new String[] {"Heure du Chili", "CLT",
                                     "Heure d'\u00e9t\u00e9 du Chili", "CLST"} ;
        String CST[] = new String[] {"Heure normale du Centre", "CST",
                                     "Heure avanc\u00e9e du Centre", "CDT"} ;
        String CTT[] = new String[] {"Heure normale de Chine", "CST",
                                     "Heure avanc\u00e9e de Chine", "CDT"} ;
        String CUBA[] = new String[] {"Heure standard de Cuba", "CST",
                                      "Heure d'\u00e9t\u00e9 de Cuba", "CDT"};
        String DARWIN[] = new String[] {"Heure standard d'Australie centrale (Territoire du Nord)", "CST",
                                        "Heure d'\u00e9t\u00e9 d'Australie centrale (Territoire du Nord)", "CST"};
        String DUBLIN[] = new String[] {"Heure du m\u00e9ridien de Greenwich", "GMT",
                                        "Heure d'\u00e9t\u00e9 irlandaise", "IST"};
        String EAT[] = new String[] {"Heure d'Afrique de l'Est", "EAT",
                                     "Heure d'\u00e9t\u00e9 d'Afrique de l'Est", "EAST"} ;
        String EASTER[] = new String[] {"Heure de l'Ile de P\u00e2ques", "EAST",
                                        "Heure d'\u00e9t\u00e9 de l'Ile de P\u00e2ques", "EASST"};
        String EET[] = new String[] {"Heure d'Europe de l'Est", "EET",
                                     "Heure d'\u00e9t\u00e9 d'Europe de l'Est", "EEST"} ;
        String EGT[] = new String[] {"Heure du Groenland de l'Est", "EGT",
                                     "Heure d'\u00e9t\u00e9 du Groenland de l'Est", "EGST"} ;
        String EST[] = new String[] {"Heure normale de l'Est", "EST",
                                     "Heure avanc\u00e9e de l'Est", "EDT"} ;
        String EST_NSW[] = new String[] {"Heure normale de l'Est (Nouvelle-Galles du Sud)", "EST",
                                         "Heure d'\u00e9t\u00e9 de l'Est (Nouvelle-Galles du Sud)", "EST"} ;
        String FET[] = new String[] {"Further-eastern European Time", "FET",
                                     "Further-eastern European Summer Time", "FEST"};
        String GHMT[] = new String[] {"Heure du Ghana", "GMT",
                                      "Heure d'\u00e9t\u00e9 du Ghana", "GHST"};
        String GAMBIER[] =  new String[] {"Heure de Gambi", "GAMT",
                                          "Heure d'\u00e9t\u00e9 de Gambi", "GAMST"};
        String GMT[] = new String[] {"Heure de Greenwich", "GMT",
                                   "Heure de Greenwich", "GMT"} ;
        String GMTBST[] = new String[] {"Heure du m\u00e9ridien de Greenwich", "GMT",
                                        "Heure d'\u00e9t\u00e9 britannique", "BST"};
        String GST[] = new String[] {"Heure normale du Golfe", "GST",
                                     "Heure avanc\u00e9e du Golfe", "GDT"} ;
        String HAST[] = new String[] {"Heure normale d'Hawa\u00ef-Al\u00e9outiennes", "HAST",
                                      "Heure avanc\u00e9e d'Hawa\u00ef-Al\u00e9outiennes", "HADT"} ;
        String HKT[] =  new String[] {"Heure de Hong Kong", "HKT",
                                      "Heure d'\u00e9t\u00e9 de Hong Kong", "HKST"};
        String HST[] = new String[] {"Heure normale d'Hawa\u00ef", "HST",
                                     "Heure avanc\u00e9e d'Hawa\u00ef", "HDT"} ;
        String ICT[] = new String[] {"Heure d'Indochine", "ICT",
                                     "Heure d'\u00e9t\u00e9 d'Indochine", "ICST"} ;
        String IRT[] = new String[] {"Heure normale d'Iran", "IRST",
                                     "Heure avanc\u00e9e d'Iran", "IRDT"} ;
        String ISRAEL[] = new String[] {"Heure standard d'Isra\u00ebl", "IST",
                                        "Heure avanc\u00e9e d'Isra\u00ebl", "IDT"};
        String IST[] = new String[] {"Heure normale d'Inde", "IST",
                                     "Heure avanc\u00e9e d'Inde", "IDT"} ;
        String JST[] = new String[] {"Heure normale du Japon", "JST",
                                     "Heure avanc\u00e9e du Japon", "JDT"} ;
        String KST[] = new String[] {"Heure normale de Cor\u00e9e", "KST",
                                     "Heure avanc\u00e9e de Cor\u00e9e", "KDT"} ;
        String LORD_HOWE[] = new String[] {"Heure standard de Lord Howe", "LHST",
                                           "Heure d'\u00e9t\u00e9 de Lord Howe", "LHST"};
        String MHT[] = new String[] {"Heure des Iles Marshall", "MHT",
                                     "Heure d'\u00e9t\u00e9 des Iles Marshall", "MHST"};
        String MSK[] = new String[] {"Heure standard de Moscou", "MSK",
                                     "Heure avanc\u00e9e de Moscou", "MSD"};
        String MST[] = new String[] {"Heure normale des Rocheuses", "MST",
                                     "Heure avanc\u00e9e des Rocheuses", "MDT"} ;
        String MYT[] = new String[] {"Heure de Malaisie", "MYT",
                                     "Heure d'\u00e9t\u00e9 de Malaisie", "MYST"};
        String NORONHA[] = new String[] {"Heure de Fernando de Noronha", "FNT",
                                         "Heure d'\u00e9t\u00e9 de Fernando de Noronha", "FNST"};
        String NOVT[] = new String[] {"Heure de Novossibirsk", "NOVT",
                                      "Heure d'\u00e9t\u00e9 de Novossibirsk", "NOVST"};
        String NPT[] = new String[] {"Heure du N\u00e9pal", "NPT",
                                     "Heure d'\u00e9t\u00e9 du N\u00e9pal", "NPST"};
        String NST[] = new String[] {"Heure normale de Terre-Neuve", "NST",
                                     "Heure avanc\u00e9e de Terre-Neuve", "NDT"} ;
        String NZST[] = new String[] {"Heure normale de Nouvelle-Z\u00e9lande", "NZST",
                                      "Heure avanc\u00e9e de Nouvelle-Z\u00e9lande", "NZDT"} ;
        String PITCAIRN[] = new String[] {"Heure standard des Pitcairn", "PST",
                                          "heure avanc\u00e9e des Pitcairn", "PDT"};
        String PKT[] = new String[] {"Heure du Pakistan", "PKT",
                                     "Heure d'\u00e9t\u00e9 du Pakistan", "PKST"} ;
        String PONT[] = new String[] {"Pohnpei Time", "PONT",
                                      "Pohnpei Summer Time", "PONST"};
        String PST[] = new String[] {"Heure normale du Pacifique", "PST",
                                     "Heure avanc\u00e9e du Pacifique", "PDT"} ;
        String SAST[] = new String[] {"Heure normale d'Afrique du Sud", "SAST",
                                      "Heure d'\u00e9t\u00e9 d'Afrique du Sud", "SAST"} ;
        String SBT[] = new String[] {"Heure des \u00celes Salomon", "SBT",
                                     "Heure d'\u00e9t\u00e9 des \u00celes Salomon", "SBST"} ;
        String SGT[] = new String[] {"Heure de Singapour", "SGT",
                                     "Heure d'\u00e9t\u00e9 de Singapour", "SGST"};
        String SLST[] = new String[] {"Heure du m\u00e9ridien de Greenwich", "GMT",
                                      "Heure d'\u00e9t\u00e9 de Sierra Leone", "SLST"};
        String TASMANIA[] = new String[] {"Heure standard d'Australie orientale (Tasmanie)", "EST",
                                          "Heure d'\u00e9t\u00e9 d'Australie orientale (Tasmanie)", "EST"};
        String TMT[] = new String[] {"Heure du Turkm\u00e9nistan", "TMT",
                                     "Heure d'\u00e9t\u00e9 du Turkm\u00e9nistan", "TMST"} ;
        String ULAT[]= new String[] {"Heure de l'Ulaanbaatar", "ULAT",
                                     "Heure d'\u00e9t\u00e9 de l'Ulaanbaatar", "ULAST"} ;
        String WART[] = new String[] {"Heure D'Argentine de l'Ouest", "WART",
                                      "Heure d'\u00e9t\u00e9 D'Argentine de l'Ouest", "WARST"} ;
        String WAT[] = new String[] {"Heure d'Afrique de l'Ouest", "WAT",
                                     "Heure d'\u00e9t\u00e9 d'Afrique de l'Ouest", "WAST"} ;
        String WET[] = new String[] {"Heure d'Europe de l'Ouest", "WET",
                                     "Heure d'\u00e9t\u00e9 d'Europe de l'Ouest", "WEST"} ;
        String WIT[] = new String[] {"Heure de l'Indon\u00e9sie occidentale", "WIT",
                                     "Heure d'\u00e9t\u00e9 de l'Indon\u00e9sie occidentale", "WIST"};
        String WST_AUS[] = new String[] {"Heure normale de l'Ouest (Australie)", "WST",
                                         "Heure d'\u00e9t\u00e9 de l'Ouest (Australie)", "WST"} ;
        String SAMOA[] = new String[] {"Heure standard de Samoa", "SST",
                                       "Heure avanc\u00e9e de Samoa", "SDT"};
        String WST_SAMOA[] = new String[] {"Heure des Samoas occidentales", "WST",
                                           "Heure d'\u00e9t\u00e9 des Samoas occidentales", "WSDT"} ;
        String ChST[] = new String[] {"Heure normale des \u00eeles Mariannes", "ChST",
                      "Heure d'\u00e9t\u00e9 des \u00eeles Mariannes", "ChDT"};
        String VICTORIA[] = new String[] {"Heure standard d'Australie orientale (Victoria)", "EST",
                                          "Heure d'\u00e9t\u00e9 d'Australie orientale (Victoria)", "EST"};
        String UTC[] = new String[] {"Temps universel coordonn\u00e9", "UTC",
                                     "Temps universel coordonn\u00e9", "UTC"};
        String UZT[] = new String[] {"Heure de l'Ouzb\u00e9kistan", "UZT",
                                     "Heure d'\u00e9t\u00e9 de l'Ouzb\u00e9kistan", "UZST"};

        return new Object[][] {
            {"America/Los_Angeles", PST},
            {"PST", PST},
            {"America/Denver", MST},
            {"MST", MST},
            {"America/Phoenix", MST},
            {"PNT", MST},
            {"America/Chicago", CST},
            {"CST", CST},
            {"America/New_York", EST},
            {"EST", EST},
            {"America/Indianapolis", EST},
            {"IET", EST},
            {"Pacific/Honolulu", HST},
            {"HST", HST},
            {"America/Anchorage", AKST},
            {"AST", AKST},
            {"America/Halifax", AST},
            {"America/Sitka", AKST},
            {"America/St_Johns", NST},
            {"CNT", NST},
            {"Europe/Paris", CET},
            {"ECT", CET},
            {"GMT", GMT},
            {"Africa/Casablanca", WET},
            {"Asia/Jerusalem", ISRAEL},
            {"Asia/Tokyo", JST},
            {"JST", JST},
            {"Europe/Bucharest", EET},
            {"Asia/Shanghai", CTT},
            {"CTT", CTT},
            /* Don't change the order of the above zones
             * to keep compatibility with the previous version.
             */

            {"ACT", DARWIN},
            {"AET", EST_NSW},
            {"AGT", AGT},
            {"ART", EET},
            {"Africa/Abidjan", GMT},
            {"Africa/Accra", GHMT},
            {"Africa/Addis_Ababa", EAT},
            {"Africa/Algiers", CET},
            {"Africa/Asmara", EAT},
            {"Africa/Asmera", EAT},
            {"Africa/Bamako", GMT},
            {"Africa/Bangui", WAT},
            {"Africa/Banjul", GMT},
            {"Africa/Bissau", GMT},
            {"Africa/Blantyre", CAT},
            {"Africa/Brazzaville", WAT},
            {"Africa/Bujumbura", CAT},
            {"Africa/Cairo", EET},
            {"Africa/Ceuta", CET},
            {"Africa/Conakry", GMT},
            {"Africa/Dakar", GMT},
            {"Africa/Dar_es_Salaam", EAT},
            {"Africa/Djibouti", EAT},
            {"Africa/Douala", WAT},
            {"Africa/El_Aaiun", WET},
            {"Africa/Freetown", SLST},
            {"Africa/Gaborone", CAT},
            {"Africa/Harare", CAT},
            {"Africa/Johannesburg", SAST},
            {"Africa/Juba", EAT},
            {"Africa/Kampala", EAT},
            {"Africa/Khartoum", EAT},
            {"Africa/Kigali", CAT},
            {"Africa/Kinshasa", WAT},
            {"Africa/Lagos", WAT},
            {"Africa/Libreville", WAT},
            {"Africa/Lome", GMT},
            {"Africa/Luanda", WAT},
            {"Africa/Lubumbashi", CAT},
            {"Africa/Lusaka", CAT},
            {"Africa/Malabo", WAT},
            {"Africa/Maputo", CAT},
            {"Africa/Maseru", SAST},
            {"Africa/Mbabane", SAST},
            {"Africa/Mogadishu", EAT},
            {"Africa/Monrovia", GMT},
            {"Africa/Nairobi", EAT},
            {"Africa/Ndjamena", WAT},
            {"Africa/Niamey", WAT},
            {"Africa/Nouakchott", GMT},
            {"Africa/Ouagadougou", GMT},
            {"Africa/Porto-Novo", WAT},
            {"Africa/Sao_Tome", GMT},
            {"Africa/Timbuktu", GMT},
            {"Africa/Tripoli", EET},
            {"Africa/Tunis", CET},
            {"Africa/Windhoek", WAT},
            {"America/Adak", HAST},
            {"America/Anguilla", AST},
            {"America/Antigua", AST},
            {"America/Araguaina", BRT},
            {"America/Argentina/Buenos_Aires", AGT},
            {"America/Argentina/Catamarca", AGT},
            {"America/Argentina/ComodRivadavia", AGT},
            {"America/Argentina/Cordoba", AGT},
            {"America/Argentina/Jujuy", AGT},
            {"America/Argentina/La_Rioja", AGT},
            {"America/Argentina/Mendoza", AGT},
            {"America/Argentina/Rio_Gallegos", AGT},
            {"America/Argentina/Salta", AGT},
            {"America/Argentina/San_Juan", AGT},
            {"America/Argentina/San_Luis", WART},
            {"America/Argentina/Tucuman", AGT},
            {"America/Argentina/Ushuaia", AGT},
            {"America/Aruba", AST},
            {"America/Asuncion", new String[] {"Heure du Paraguay", "PYT",
                                               "Heure d'\u00e9t\u00e9 du Paraguay", "PYST"}},
            {"America/Atikokan", EST},
            {"America/Atka", HAST},
            {"America/Bahia", BRT},
            {"America/Bahia_Banderas", CST},
            {"America/Barbados", AST},
            {"America/Belem", BRT},
            {"America/Belize", CST},
            {"America/Blanc-Sablon", AST},
            {"America/Boa_Vista", AMT},
            {"America/Bogota", new String[] {"Heure de Colombie", "COT",
                                             "Heure d'\u00e9t\u00e9 de Colombie", "COST"}},
            {"America/Boise", MST},
            {"America/Buenos_Aires", AGT},
            {"America/Cambridge_Bay", MST},
            {"America/Campo_Grande", AMT},
            {"America/Cancun", CST},
            {"America/Caracas", new String[] {"Heure du Venezuela", "VET",
                                              "Heure d'\u00e9t\u00e9 du Venezuela", "VEST"}},
            {"America/Catamarca", AGT},
            {"America/Cayenne", new String[] {"Heure de Guyane fran\u00e7aise", "GFT",
                                              "Heure d'\u00e9t\u00e9 de Guyane fran\u00e7aise", "GFST"}},
            {"America/Cayman", EST},
            {"America/Chihuahua", MST},
            {"America/Creston", MST},
            {"America/Coral_Harbour", EST},
            {"America/Cordoba", AGT},
            {"America/Costa_Rica", CST},
            {"America/Cuiaba", AMT},
            {"America/Curacao", AST},
            {"America/Danmarkshavn", GMT},
            {"America/Dawson", PST},
            {"America/Dawson_Creek", MST},
            {"America/Detroit", EST},
            {"America/Dominica", AST},
            {"America/Edmonton", MST},
            {"America/Eirunepe", AMT},
            {"America/El_Salvador", CST},
            {"America/Ensenada", PST},
            {"America/Fort_Wayne", EST},
            {"America/Fortaleza", BRT},
            {"America/Glace_Bay", AST},
            {"America/Godthab", new String[] {"Heure du Groenland de l'Ouest", "WGT",
                                              "Heure d'\u00e9t\u00e9 du Groenland de l'Ouest", "WGST"}},
            {"America/Goose_Bay", AST},
            {"America/Grand_Turk", EST},
            {"America/Grenada", AST},
            {"America/Guadeloupe", AST},
            {"America/Guatemala", CST},
            {"America/Guayaquil", new String[] {"Heure de l'\u00c9quateur", "ECT",
                                                "Heure d'\u00e9t\u00e9 de l'\u00c9quateur", "ECST"}},
            {"America/Guyana", new String[] {"Heure de Guyana", "GYT",
                                             "Heure d'\u00e9t\u00e9 de Guyana", "GYST"}},
            {"America/Havana", CUBA},
            {"America/Hermosillo", MST},
            {"America/Indiana/Indianapolis", EST},
            {"America/Indiana/Knox", CST},
            {"America/Indiana/Marengo", EST},
            {"America/Indiana/Petersburg", EST},
            {"America/Indiana/Tell_City", CST},
            {"America/Indiana/Vevay", EST},
            {"America/Indiana/Vincennes", EST},
            {"America/Indiana/Winamac", EST},
            {"America/Inuvik", MST},
            {"America/Iqaluit", EST},
            {"America/Jamaica", EST},
            {"America/Jujuy", AGT},
            {"America/Juneau", AKST},
            {"America/Kentucky/Louisville", EST},
            {"America/Kentucky/Monticello", EST},
            {"America/Knox_IN", CST},
            {"America/Kralendijk", AST},
            {"America/La_Paz", new String[] {"Heure de Bolivie", "BOT",
                                             "Heure d'\u00e9t\u00e9 de Bolivie", "BOST"}},
            {"America/Lima", new String[] {"Heure du P\u00e9rou", "PET",
                                           "Heure d'\u00e9t\u00e9 du P\u00e9rou", "PEST"}},
            {"America/Louisville", EST},
            {"America/Lower_Princes", AST},
            {"America/Maceio", BRT},
            {"America/Managua", CST},
            {"America/Manaus", AMT},
            {"America/Marigot", AST},
            {"America/Martinique", AST},
            {"America/Matamoros", CST},
            {"America/Mazatlan", MST},
            {"America/Mendoza", AGT},
            {"America/Menominee", CST},
            {"America/Merida", CST},
            {"America/Metlakatla", new String[] {"Metlakatla Standard Time", "MeST",
                                                 "Metlakatla Daylight Time", "MeDT"}},
            {"America/Mexico_City", CST},
            {"America/Miquelon", new String[] {"Heure normale de Saint-Pierre et Miquelon", "PMST",
                                               "Heure avanc\u00e9e de Saint-Pierre et Miquelon", "PMDT"}},
            {"America/Moncton", AST},
            {"America/Montevideo", new String[] {"Heure de l'Uruguay", "UYT",
                                                 "Heure d'\u00e9t\u00e9 de l'Uruguay", "UYST"}},
            {"America/Monterrey", CST},
            {"America/Montreal", EST},
            {"America/Montserrat", AST},
            {"America/Nassau", EST},
            {"America/Nipigon", EST},
            {"America/Nome", AKST},
            {"America/Noronha", NORONHA},
            {"America/North_Dakota/Beulah", CST},
            {"America/North_Dakota/Center", CST},
            {"America/North_Dakota/New_Salem", CST},
            {"America/Ojinaga", MST},
            {"America/Panama", EST},
            {"America/Pangnirtung", EST},
            {"America/Paramaribo", new String[] {"Heure du Surinam", "SRT",
                                                 "Heure d'\u00e9t\u00e9 du Surinam", "SRST"}},
            {"America/Port-au-Prince", EST},
            {"America/Port_of_Spain", AST},
            {"America/Porto_Acre", AMT},
            {"America/Porto_Velho", AMT},
            {"America/Puerto_Rico", AST},
            {"America/Rainy_River", CST},
            {"America/Rankin_Inlet", CST},
            {"America/Recife", BRT},
            {"America/Regina", CST},
            {"America/Resolute", CST},
            {"America/Rio_Branco", AMT},
            {"America/Rosario", AGT},
            {"America/Santa_Isabel", PST},
            {"America/Santarem", BRT},
            {"America/Santiago", CLT},
            {"America/Santo_Domingo", AST},
            {"America/Sao_Paulo", BRT},
            {"America/Scoresbysund", EGT},
            {"America/Shiprock", MST},
            {"America/St_Barthelemy", AST},
            {"America/St_Kitts", AST},
            {"America/St_Lucia", AST},
            {"America/St_Thomas", AST},
            {"America/St_Vincent", AST},
            {"America/Swift_Current", CST},
            {"America/Tegucigalpa", CST},
            {"America/Thule", AST},
            {"America/Thunder_Bay", EST},
            {"America/Tijuana", PST},
            {"America/Toronto", EST},
            {"America/Tortola", AST},
            {"America/Vancouver", PST},
            {"America/Virgin", AST},
            {"America/Whitehorse", PST},
            {"America/Winnipeg", CST},
            {"America/Yakutat", AKST},
            {"America/Yellowknife", MST},
            {"Antarctica/Casey", WST_AUS},
            {"Antarctica/Davis", new String[] {"Heure de Davis", "DAVT",
                                               "Heure d'\u00e9t\u00e9 de Davis", "DAVST"}},
            {"Antarctica/DumontDUrville", new String[] {"Heure de Dumont-d'Urville", "DDUT",
                                                        "Heure d'\u00e9t\u00e9 de Dumont-d'Urville", "DDUST"}},
            {"Antarctica/Macquarie", new String[] {"Macquarie Island Time", "MIST",
                                                   "Macquarie Island Summer Time", "MIST"}},
            {"Antarctica/Mawson", new String[] {"Heure de Mawson", "MAWT",
                                                "Heure d'\u00e9t\u00e9 de Mawson", "MAWST"}},
            {"Antarctica/McMurdo", NZST},
            {"Antarctica/Palmer", CLT},
            {"Antarctica/Rothera", new String[] {"Heure de Rothera", "ROTT",
                                                 "Heure d'\u00e9t\u00e9 de Rothera", "ROTST"}},
            {"Antarctica/South_Pole", NZST},
            {"Antarctica/Syowa", new String[] {"Heure de Syowa", "SYOT",
                                               "Heure d'\u00e9t\u00e9 de Syowa", "SYOST"}},
            {"Antarctica/Vostok", new String[] {"Heure de Vostok", "VOST",
                                                "Heure d'\u00e9t\u00e9 de Vostok", "VOSST"}},
            {"Arctic/Longyearbyen", CET},
            {"Asia/Aden", ARAST},
            {"Asia/Almaty", new String[] {"Heure d'Alma-Ata", "ALMT",
                                          "Heure d'\u00e9t\u00e9 d'Alma-Ata", "ALMST"}},
            {"Asia/Amman", EET},
            {"Asia/Anadyr", new String[] {"Heure d'Anadyr", "ANAT",
                                          "Heure d'\u00e9t\u00e9 d'Anadyr", "ANAST"}},
            {"Asia/Aqtau", new String[] {"Heure d'Aqtau", "AQTT",
                                         "Heure d'\u00e9t\u00e9 d'Aqtau", "AQTST"}},
            {"Asia/Aqtobe", new String[] {"Heure d'Aqtobe", "AQTT",
                                          "Heure d'\u00e9t\u00e9 d'Aqtobe", "AQTST"}},
            {"Asia/Ashgabat", TMT},
            {"Asia/Ashkhabad", TMT},
            {"Asia/Baghdad", ARAST},
            {"Asia/Bahrain", ARAST},
            {"Asia/Baku", new String[] {"Heure d'Azerba\u00efdjan", "AZT",
                                        "Heure d'\u00e9t\u00e9 d'Azerba\u00efdjan", "AZST"}},
            {"Asia/Bangkok", ICT},
            {"Asia/Beirut", EET},
            {"Asia/Bishkek", new String[] {"Heure du Kirghizistan", "KGT",
                                           "Heure d'\u00e9t\u00e9 du Kirghizistan", "KGST"}},
            {"Asia/Brunei", new String[] {"Heure du Brunei", "BNT",
                                          "Heure d'\u00e9t\u00e9 du Brunei", "BNST"}},
            {"Asia/Calcutta", IST},
            {"Asia/Choibalsan", new String[] {"Heure de Choibalsan", "CHOT",
                                              "Heure d'\u00e9t\u00e9 de Choibalsan", "CHOST"}},
            {"Asia/Chongqing", CTT},
            {"Asia/Chungking", CTT},
            {"Asia/Colombo", IST},
            {"Asia/Dacca", BDT},
            {"Asia/Dhaka", BDT},
            {"Asia/Dili", new String[] {"Heure de Timor-Leste", "TLT",
                                        "Heure d'\u00e9t\u00e9 de Timor-Leste", "TLST"}},
            {"Asia/Damascus", EET},
            {"Asia/Dubai", GST},
            {"Asia/Dushanbe", new String[] {"Heure du Tadjikistan", "TJT",
                                            "Heure d'\u00e9t\u00e9 du Tadjikistan", "TJST"}},
            {"Asia/Gaza", EET},
            {"Asia/Harbin", CTT},
            {"Asia/Hebron", EET},
            {"Asia/Ho_Chi_Minh", ICT},
            {"Asia/Hong_Kong", HKT},
            {"Asia/Hovd", new String[] {"Heure de Hovd", "HOVT",
                                        "Heure d'\u00e9t\u00e9 de Hovd", "HOVST"}},
            {"Asia/Irkutsk", new String[] {"Heure d'Irkutsk", "IRKT",
                                           "Heure d'\u00e9t\u00e9 d'Irkutsk", "IRKST"}},
            {"Asia/Istanbul", EET},
            {"Asia/Jakarta", WIT},
            {"Asia/Jayapura", new String[] {"Heure d'Indon\u00e9sie orientale", "EIT",
                                            "Heure d'\u00e9t\u00e9 d'Indon\u00e9sie orientale", "EIST"}},
            {"Asia/Kabul", new String[] {"Heure d'Afghanistan", "AFT",
                                         "Heure d'\u00e9t\u00e9 d'Afghanistan", "AFST"}},
            {"Asia/Kamchatka", new String[] {"Heure de Petropavlovsk-Kamchatski", "PETT",
                                             "Heure d'\u00e9t\u00e9 de Petropavlovsk-Kamchatski", "PETST"}},
            {"Asia/Karachi", PKT},
            {"Asia/Kashgar", CTT},
            {"Asia/Kathmandu", NPT},
            {"Asia/Katmandu", NPT},
            {"Asia/Kolkata", IST},
            {"Asia/Krasnoyarsk", new String[] {"Heure de Krasno\u00efarsk", "KRAT",
                                               "Heure d'\u00e9t\u00e9 de Krasno\u00efarsk", "KRAST"}},
            {"Asia/Kuala_Lumpur", MYT},
            {"Asia/Kuching", MYT},
            {"Asia/Kuwait", ARAST},
            {"Asia/Macao", CTT},
            {"Asia/Macau", CTT},
            {"Asia/Magadan", new String[] {"Heure de Magadan", "MAGT",
                                           "Heure d'\u00e9t\u00e9 de Magadan", "MAGST"}},
            {"Asia/Makassar", CIT},
            {"Asia/Manila", new String[] {"Heure des Philippines", "PHT",
                                          "Heure d'\u00e9t\u00e9 des Philippines", "PHST"}},
            {"Asia/Muscat", GST},
            {"Asia/Nicosia", EET},
            {"Asia/Novokuznetsk", NOVT},
            {"Asia/Novosibirsk", NOVT},
            {"Asia/Oral", new String[] {"Heure d'Oral", "ORAT",
                                        "Heure d'\u00e9t\u00e9 d'Oral", "ORAST"}},
            {"Asia/Omsk", new String[] {"Heure d'Omsk", "OMST",
                                        "Heure d'\u00e9t\u00e9 d'Omsk", "OMSST"}},
            {"Asia/Phnom_Penh", ICT},
            {"Asia/Pontianak", WIT},
            {"Asia/Pyongyang", KST},
            {"Asia/Qatar", ARAST},
            {"Asia/Qyzylorda", new String[] {"Heure de Kyzylorda", "QYZT",
                                             "Heure d'\u00e9t\u00e9 de Kyzylorda", "QYZST"}},
            {"Asia/Rangoon", new String[] {"Heure de Myanmar", "MMT",
                                           "Heure d'\u00e9t\u00e9 de Myanmar", "MMST"}},
            {"Asia/Riyadh", ARAST},
            {"Asia/Saigon", ICT},
            {"Asia/Sakhalin", new String[] {"Heure de Sakhalin", "SAKT",
                                            "Heure d'\u00e9t\u00e9 de Sakhalin", "SAKST"}},
            {"Asia/Samarkand", UZT},
            {"Asia/Seoul", KST},
            {"Asia/Singapore", SGT},
            {"Asia/Taipei", CTT},
            {"Asia/Tel_Aviv", ISRAEL},
            {"Asia/Tashkent", UZT},
            {"Asia/Tbilisi", new String[] {"Heure de G\u00e9orgie", "GET",
                                           "Heure d'\u00e9t\u00e9 de G\u00e9orgie", "GEST"}},
            {"Asia/Tehran", IRT},
            {"Asia/Thimbu", BTT},
            {"Asia/Thimphu", BTT},
            {"Asia/Ujung_Pandang", CIT},
            {"Asia/Ulaanbaatar", ULAT},
            {"Asia/Ulan_Bator", ULAT},
            {"Asia/Urumqi", CTT},
            {"Asia/Vientiane", ICT},
            {"Asia/Vladivostok", new String[] {"Heure de Vladivostok", "VLAT",
                                               "Heure d'\u00e9t\u00e9 de Vladivostok", "VLAST"}},
            {"Asia/Yakutsk", new String[] {"Heure du Iakoutsk", "YAKT",
                                           "Heure d'\u00e9t\u00e9 du Iakoutsk", "YAKST"}},
            {"Asia/Yekaterinburg", new String[] {"Heure de Yekaterinburg", "YEKT",
                                                 "Heure d'\u00e9t\u00e9 de Yekaterinburg", "YEKST"}},
            {"Asia/Yerevan", ARMT},
            {"Atlantic/Azores", new String[] {"Heure des A\u00e7ores", "AZOT",
                                              "Heure d'\u00e9t\u00e9 des A\u00e7ores", "AZOST"}},
            {"Atlantic/Bermuda", AST},
            {"Atlantic/Canary", WET},
            {"Atlantic/Cape_Verde", new String[] {"Heure de Cap-Vert", "CVT",
                                                  "Heure d'\u00e9t\u00e9 de Cap-Vert", "CVST"}},
            {"Atlantic/Faeroe", WET},
            {"Atlantic/Faroe", WET},
            {"Atlantic/Jan_Mayen", CET},
            {"Atlantic/Madeira", WET},
            {"Atlantic/Reykjavik", GMT},
            {"Atlantic/South_Georgia", new String[] {"Heure normale de G\u00e9orgie du Sud", "GST",
                                                     "Heure avanc\u00e9e de G\u00e9orgie du Sud", "GDT"}},
            {"Atlantic/St_Helena", GMT},
            {"Atlantic/Stanley", new String[] {"Heure des \u00eeles Falkland", "FKT",
                                               "Heure d'\u00e9t\u00e9 des \u00eeles Falkland", "FKST"}},
            {"Australia/ACT", EST_NSW},
            {"Australia/Adelaide", ADELAIDE},
            {"Australia/Brisbane", BRISBANE},
            {"Australia/Broken_Hill", BROKEN_HILL},
            {"Australia/Canberra", EST_NSW},
            {"Australia/Currie", EST_NSW},
            {"Australia/Darwin", DARWIN},
            {"Australia/Eucla", new String[] {"Heure standard de l'Australie occidentale (centre)", "CWST",
                                              "Heure d'\u00e9t\u00e9 de l'Australie occidentale (centre)", "CWST"}},
            {"Australia/Hobart", TASMANIA},
            {"Australia/LHI", LORD_HOWE},
            {"Australia/Lindeman", BRISBANE},
            {"Australia/Lord_Howe", LORD_HOWE},
            {"Australia/Melbourne", VICTORIA},
            {"Australia/North", DARWIN},
            {"Australia/NSW", EST_NSW},
            {"Australia/Perth", WST_AUS},
            {"Australia/Queensland", BRISBANE},
            {"Australia/South", ADELAIDE},
            {"Australia/Sydney", EST_NSW},
            {"Australia/Tasmania", TASMANIA},
            {"Australia/Victoria", VICTORIA},
            {"Australia/West", WST_AUS},
            {"Australia/Yancowinna", BROKEN_HILL},
            {"BET", BRT},
            {"BST", BDT},
            {"Brazil/Acre", AMT},
            {"Brazil/DeNoronha", NORONHA},
            {"Brazil/East", BRT},
            {"Brazil/West", AMT},
            {"Canada/Atlantic", AST},
            {"Canada/Central", CST},
            {"Canada/East-Saskatchewan", CST},
            {"Canada/Eastern", EST},
            {"Canada/Mountain", MST},
            {"Canada/Newfoundland", NST},
            {"Canada/Pacific", PST},
            {"Canada/Yukon", PST},
            {"Canada/Saskatchewan", CST},
            {"CAT", CAT},
            {"CET", CET},
            {"Chile/Continental", CLT},
            {"Chile/EasterIsland", EASTER},
            {"CST6CDT", CST},
            {"Cuba", CUBA},
            {"EAT", EAT},
            {"EET", EET},
            {"Egypt", EET},
            {"Eire", DUBLIN},
            {"EST5EDT", EST},
            {"Etc/Greenwich", GMT},
            {"Etc/UCT", UTC},
            {"Etc/Universal", UTC},
            {"Etc/UTC", UTC},
            {"Etc/Zulu", UTC},
            {"Europe/Amsterdam", CET},
            {"Europe/Andorra", CET},
            {"Europe/Athens", EET},
            {"Europe/Belfast", GMTBST},
            {"Europe/Belgrade", CET},
            {"Europe/Berlin", CET},
            {"Europe/Bratislava", CET},
            {"Europe/Brussels", CET},
            {"Europe/Budapest", CET},
            {"Europe/Chisinau", EET},
            {"Europe/Copenhagen", CET},
            {"Europe/Dublin", DUBLIN},
            {"Europe/Gibraltar", CET},
            {"Europe/Guernsey", GMTBST},
            {"Europe/Helsinki", EET},
            {"Europe/Isle_of_Man", GMTBST},
            {"Europe/Istanbul", EET},
            {"Europe/Jersey", GMTBST},
            {"Europe/Kaliningrad", FET},
            {"Europe/Kiev", EET},
            {"Europe/Lisbon", WET},
            {"Europe/Ljubljana", CET},
            {"Europe/London", GMTBST},
            {"Europe/Luxembourg", CET},
            {"Europe/Madrid", CET},
            {"Europe/Malta", CET},
            {"Europe/Mariehamn", EET},
            {"Europe/Minsk", FET},
            {"Europe/Monaco", CET},
            {"Europe/Moscow", MSK},
            {"Europe/Nicosia", EET},
            {"Europe/Oslo", CET},
            {"Europe/Podgorica", CET},
            {"Europe/Prague", CET},
            {"Europe/Riga", EET},
            {"Europe/Rome", CET},
            {"Europe/Samara", new String[] {"Heure normale de Samara", "SAMT",
                                            "Heure d'\u00e9t\u00e9 de Samara", "SAMST"}},
            {"Europe/San_Marino", CET},
            {"Europe/Sarajevo", CET},
            {"Europe/Simferopol", EET},
            {"Europe/Skopje", CET},
            {"Europe/Sofia", EET},
            {"Europe/Stockholm", CET},
            {"Europe/Tallinn", EET},
            {"Europe/Tirane", CET},
            {"Europe/Tiraspol", EET},
            {"Europe/Uzhgorod", EET},
            {"Europe/Vaduz", CET},
            {"Europe/Vatican", CET},
            {"Europe/Vienna", CET},
            {"Europe/Vilnius", EET},
            {"Europe/Volgograd", new String[] {"Heure de Volgograd", "VOLT",
                                               "Heure d'\u00e9t\u00e9 de Volgograd", "VOLST"}},
            {"Europe/Warsaw", CET},
            {"Europe/Zagreb", CET},
            {"Europe/Zaporozhye", EET},
            {"Europe/Zurich", CET},
            {"GB", GMTBST},
            {"GB-Eire", GMTBST},
            {"Greenwich", GMT},
            {"Hongkong", HKT},
            {"Iceland", GMT},
            {"Iran", IRT},
            {"IST", IST},
            {"Indian/Antananarivo", EAT},
            {"Indian/Chagos", new String[] {"Heure de l'oc\u00e9an Indien", "IOT",
                                            "Heure d'\u00e9t\u00e9 de l'oc\u00e9an Indien", "IOST"}},
            {"Indian/Christmas", new String[] {"Heure de l'\u00cele Christmas", "CXT",
                                               "Heure d'\u00e9t\u00e9 de l'\u00cele Christmas", "CXST"}},
            {"Indian/Cocos", new String[] {"Heure des \u00celes Cocos", "CCT",
                                           "Heure d'\u00e9t\u00e9 des \u00celes Cocos", "CCST"}},
            {"Indian/Comoro", EAT},
            {"Indian/Kerguelen", new String[] {"Heure des Terres australes antartiques fran\u00e7aises", "TFT",
                                               "Heure d'\u00e9t\u00e9 des Terres australes antartiques fran\u00e7aises", "TFST"}},
            {"Indian/Mahe", new String[] {"Heure des Seychelles", "SCT",
                                          "Heure d'\u00e9t\u00e9 des Seychelles", "SCST"}},
            {"Indian/Maldives", new String[] {"Heure des Maldives", "MVT",
                                              "Heure d'\u00e9t\u00e9 des Maldives", "MVST"}},
            {"Indian/Mauritius", new String[] {"Heure de Maurice", "MUT",
                                               "Heure d'\u00e9t\u00e9 de Maurice", "MUST"}},
            {"Indian/Mayotte", EAT},
            {"Indian/Reunion", new String[] {"Heure de la R\u00e9union", "RET",
                                             "Heure d'\u00e9t\u00e9 de la R\u00e9union", "REST"}},
            {"Israel", ISRAEL},
            {"Jamaica", EST},
            {"Japan", JST},
            {"Kwajalein", MHT},
            {"Libya", EET},
            {"MET", new String[] {"Heure de l'Europe centrale", "MET",
                                  "Heure d'\u00e9t\u00e9 de l'Europe centrale", "MEST"}},
            {"Mexico/BajaNorte", PST},
            {"Mexico/BajaSur", MST},
            {"Mexico/General", CST},
            {"MIT", WST_SAMOA},
            {"MST7MDT", MST},
            {"Navajo", MST},
            {"NET", ARMT},
            {"NST", NZST},
            {"NZ", NZST},
            {"NZ-CHAT", CHAST},
            {"PLT", PKT},
            {"Portugal", WET},
            {"PRT", AST},
            {"Pacific/Apia", WST_SAMOA},
            {"Pacific/Auckland", NZST},
            {"Pacific/Chatham", CHAST},
            {"Pacific/Chuuk", CHUT},
            {"Pacific/Easter", EASTER},
            {"Pacific/Efate", new String[] {"Heure du Vanuatu", "VUT",
                                            "Heure d'\u00e9t\u00e9 du Vanuatu", "VUST"}},
            {"Pacific/Enderbury", new String[] {"Heure de l'\u00cele de Phoenix", "PHOT",
                                                "Heure d'\u00e9t\u00e9 de l'\u00cele de Phoenix", "PHOST"}},
            {"Pacific/Fakaofo", new String[] {"Heure de Tokelau", "TKT",
                                              "Heure d'\u00e9t\u00e9 de Tokelau", "TKST"}},
            {"Pacific/Fiji", new String[] {"Heure de Fidji", "FJT",
                                           "Heure d'\u00e9t\u00e9 de Fidji", "FJST"}},
            {"Pacific/Funafuti", new String[] {"Heure de Tuvalu", "TVT",
                                               "Heure d'\u00e9t\u00e9 de Tuvalu", "TVST"}},
            {"Pacific/Galapagos", new String[] {"Heure des Galapagos", "GALT",
                                                "Heure d'\u00e9t\u00e9 des Galapagos", "GALST"}},
            {"Pacific/Gambier", GAMBIER},
            {"Pacific/Guadalcanal", SBT},
            {"Pacific/Guam", ChST},
            {"Pacific/Johnston", HST},
            {"Pacific/Kiritimati", new String[] {"Heure de l'\u00cele de Line", "LINT",
                                                 "Heure d'\u00e9t\u00e9 de l'\u00cele de Line", "LINST"}},
            {"Pacific/Kosrae", new String[] {"Heure de Kusaie", "KOST",
                                             "Heure d'\u00e9t\u00e9 de Kusaie", "KOSST"}},
            {"Pacific/Kwajalein", MHT},
            {"Pacific/Majuro", MHT},
            {"Pacific/Marquesas", new String[] {"Heure des Marquises", "MART",
                                                "Heure d'\u00e9t\u00e9 des Marquises", "MARST"}},
            {"Pacific/Midway", SAMOA},
            {"Pacific/Nauru", new String[] {"Heure de Nauru", "NRT",
                                            "Heure d'\u00e9t\u00e9 de Nauru", "NRST"}},
            {"Pacific/Niue", new String[] {"Heure de Niue", "NUT",
                                           "Heure d'\u00e9t\u00e9 de Niue", "NUST"}},
            {"Pacific/Norfolk", new String[] {"Heure de Norfolk", "NFT",
                                              "Heure d'\u00e9t\u00e9 de Norfolk", "NFST"}},
            {"Pacific/Noumea", new String[] {"Heure de Nouvelle-Cal\u00e9donie", "NCT",
                                             "Heure d'\u00e9t\u00e9 de Nouvelle-Cal\u00e9donie", "NCST"}},
            {"Pacific/Pago_Pago", SAMOA},
            {"Pacific/Palau", new String[] {"Heure de Palaos", "PWT",
                                            "Heure d'\u00e9t\u00e9 de Palaos", "PWST"}},
            {"Pacific/Pitcairn", PITCAIRN},
            {"Pacific/Pohnpei", PONT},
            {"Pacific/Ponape", PONT},
            {"Pacific/Port_Moresby", new String[] {"Heure de Papouasie-Nouvelle-Guin\u00e9e", "PGT",
                                                   "Heure d'\u00e9t\u00e9 de de Papouasie-Nouvelle-Guin\u00e9e", "PGST"}},
            {"Pacific/Rarotonga", new String[] {"Heure des \u00celes Cook", "CKT",
                                                "Heure d'\u00e9t\u00e9 des \u00celes Cook", "CKHST"}},
            {"Pacific/Saipan", ChST},
            {"Pacific/Samoa", SAMOA},
            {"Pacific/Tahiti", new String[] {"Heure de Tahiti", "TAHT",
                                             "Heure d'\u00e9t\u00e9 de Tahiti", "TAHST"}},
            {"Pacific/Tarawa", new String[] {"Heure de Kiribati", "GILT",
                                             "Heure d'\u00e9t\u00e9 de Kiribati", "GILST"}},
            {"Pacific/Tongatapu", new String[] {"Heure de Tonga", "TOT",
                                                "Heure d'\u00e9t\u00e9 de Tonga", "TOST"}},
            {"Pacific/Truk", CHUT},
            {"Pacific/Wake", new String[] {"Heure de Wake", "WAKT",
                                           "Heure d'\u00e9t\u00e9 de Wake", "WAKST"}},
            {"Pacific/Wallis", new String[] {"Heure de Wallis et Futuna", "WFT",
                                             "Heure d'\u00e9t\u00e9 de Wallis et Futuna", "WFST"}},
            {"Pacific/Yap", CHUT},
            {"Poland", CET},
            {"PRC", CTT},
            {"PST8PDT", PST},
            {"ROK", KST},
            {"Singapore", SGT},
            {"SST", SBT},
            {"SystemV/AST4", AST},
            {"SystemV/AST4ADT", AST},
            {"SystemV/CST6", CST},
            {"SystemV/CST6CDT", CST},
            {"SystemV/EST5", EST},
            {"SystemV/EST5EDT", EST},
            {"SystemV/HST10", HST},
            {"SystemV/MST7", MST},
            {"SystemV/MST7MDT", MST},
            {"SystemV/PST8", PST},
            {"SystemV/PST8PDT", PST},
            {"SystemV/YST9", AKST},
            {"SystemV/YST9YDT", AKST},
            {"Turkey", EET},
            {"UCT", UTC},
            {"Universal", UTC},
            {"US/Alaska", AKST},
            {"US/Aleutian", HAST},
            {"US/Arizona", MST},
            {"US/Central", CST},
            {"US/Eastern", EST},
            {"US/Hawaii", HST},
            {"US/Indiana-Starke", CST},
            {"US/East-Indiana", EST},
            {"US/Michigan", EST},
            {"US/Mountain", MST},
            {"US/Pacific", PST},
            {"US/Pacific-New", PST},
            {"US/Samoa", SAMOA},
            {"UTC", UTC},
            {"VST", ICT},
            {"W-SU", MSK},
            {"WET", WET},
            {"Zulu", UTC},
        };
    }
}
