/*
 * Copyright (c) 1997, 2010, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

/*
 * (C) Copyright Taligent, Inc. 1996, 1997 - All Rights Reserved
 * (C) Copyright IBM Corp. 1996 - 1998 - All Rights Reserved
 *
 * The original version of this source code and documentation
 * is copyrighted and owned by Taligent, Inc., a wholly-owned
 * subsidiary of IBM. These materials are provided under terms
 * of a License Agreement between Taligent and Sun. This technology
 * is protected by multiple US and International patents.
 *
 * This notice and attribution to Taligent may not be removed.
 * Taligent is a registered trademark of Taligent, Inc.
 *
 */

package sun.util.resources;

public final class TimeZoneNames_pt_BR extends TimeZoneNamesBundle {

    protected final Object[][] getContents() {
    String ACT[] = new String[] {"Fuso hor\u00e1rio do Acre", "ACT",
                     "Fuso hor\u00e1rio de ver\u00e3o do Acre", "ACST"};
    String ADELAIDE[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o central (Austr\u00e1lia do Sul)", "CST",
                      "Fuso hor\u00e1rio de ver\u00e3o central (Austr\u00e1lia do Sul)", "CST"};
    String AGT[] = new String[] {"Fuso hor\u00e1rio da Argentina", "ART",
                     "Fuso hor\u00e1rio de ver\u00e3o da Argentina", "ARST"};
    String AKST[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o do Alaska", "AKST",
                      "Hor\u00e1rio de luz natural do Alaska", "AKDT"};
    String AMT[] = new String[] {"Fuso hor\u00e1rio do Amazonas", "AMT",
                     "Fuso hor\u00e1rio de ver\u00e3o do Amazonas", "AMST"};
    String ARAST[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o da Ar\u00e1bia", "AST",
                       "Hor\u00e1rio de luz natural da Ar\u00e1bia", "ADT"};
    String ARMT[] = new String[] {"Fuso hor\u00e1rio da Arm\u00eania", "AMT",
                      "Fuso hor\u00e1rio de ver\u00e3o da Arm\u00eania", "AMST"};
    String AST[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o do Atl\u00e2ntico", "AST",
                     "Hor\u00e1rio de luz natural do Atl\u00e2ntico", "ADT"};
    String BDT[] = new String[] {"Fuso hor\u00e1rio de Bangladesh", "BDT",
                     "Fuso hor\u00e1rio de ver\u00e3o de Bangladesh", "BDST"};
    String BRISBANE[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o oriental (Queensland)", "EST",
                      "Fuso hor\u00e1rio de ver\u00e3o oriental (Queensland)", "EST"};
    String BROKEN_HILL[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o central (Austr\u00e1lia do Sul/Nova Gales do Sul)", "CST",
                         "Fuso hor\u00e1rio de ver\u00e3o central (Austr\u00e1lia do Sul/Nova Gales do Sul)", "CST"};
    String BRT[] = new String[] {"Fuso hor\u00e1rio de Bras\u00edlia", "BRT",
                     "Fuso hor\u00e1rio de ver\u00e3o de Bras\u00edlia", "BRST"};
    String BTT[] = new String[] {"Fuso hor\u00e1rio de But\u00e3o", "BTT",
                     "Fuso hor\u00e1rio de ver\u00e3o de But\u00e3o", "BTST"};
    String CAT[] = new String[] {"Fuso hor\u00e1rio da \u00c1frica Central", "CAT",
                     "Fuso hor\u00e1rio de ver\u00e3o da \u00c1frica Central", "CAST"};
    String CET[] = new String[] {"Fuso hor\u00e1rio da Europa Central", "CET",
                     "Fuso hor\u00e1rio de ver\u00e3o da Europa Central", "CEST"};
    String CHAST[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o de Chatham", "CHAST",
                       "Hor\u00e1rio de luz natural de Chatham", "CHADT"};
    String CIT[] = new String[] {"Fuso hor\u00e1rio da Indon\u00e9sia Central", "CIT",
                     "Fuso hor\u00e1rio de ver\u00e3o da Indon\u00e9sia Central", "CIST"};
    String CLT[] = new String[] {"Fuso hor\u00e1rio do Chile", "CLT",
                     "Fuso hor\u00e1rio de ver\u00e3o do Chile", "CLST"};
    String CST[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o central", "CST",
                     "Hor\u00e1rio de luz natural central", "CDT"};
    String CTT[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o da China", "CST",
                     "Hor\u00e1rio de luz natural da China", "CDT"};
    String CUBA[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o de Cuba", "CST",
                      "Hor\u00e1rio de luz natural de Cuba", "CDT"};
    String DARWIN[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o central (Territ\u00f3rio do Norte)", "CST",
                    "Fuso hor\u00e1rio de ver\u00e3o central (Territ\u00f3rio do Norte)", "CST"};
    String DUBLIN[] = new String[] {"Fuso hor\u00e1rio do meridiano de Greenwich", "GMT",
                    "Fuso hor\u00e1rio de ver\u00e3o da Irlanda", "IST"};
    String EAT[] = new String[] {"Fuso hor\u00e1rio da \u00c1frica Oriental", "EAT",
                     "Fuso hor\u00e1rio padr\u00e3o da \u00c1frica Oriental", "EAST"};
    String EASTER[] = new String[] {"Fuso hor\u00e1rio da Ilha de P\u00e1scoa", "EAST",
                    "Fuso hor\u00e1rio de ver\u00e3o da Ilha de P\u00e1scoa", "EASST"};
    String EET[] = new String[] {"Fuso hor\u00e1rio da Europa Oriental", "EET",
                     "Fuso hor\u00e1rio de ver\u00e3o da Europa Oriental", "EEST"};
    String EGT[] = new String[] {"Fuso hor\u00e1rio da Groenl\u00e2ndia Oriental", "EGT",
                     "Fuso hor\u00e1rio de ver\u00e3o da Groenl\u00e2ndia Oriental", "EGST"};
    String EST[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o oriental", "EST",
                     "Hor\u00e1rio de luz natural oriental", "EDT"};
    String EST_NSW[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o oriental (Nova Gales do Sul)", "EST",
                     "Fuso hor\u00e1rio de ver\u00e3o oriental (Nova Gales do Sul)", "EST"};
    String GHMT[] = new String[] {"Fuso hor\u00e1rio do meridiano de Gana", "GMT",
                     "Fuso hor\u00e1rio de ver\u00e3o de Gana", "GHST"};
    String GAMBIER[] =  new String[] {"Fuso hor\u00e1rio de Gambier", "GAMT",
                      "Fuso hor\u00e1rio de ver\u00e3o de Gambier", "GAMST"};
    String GMT[] = new String[] {"Fuso hor\u00e1rio do meridiano de Greenwich", "GMT",
                     "Fuso hor\u00e1rio do meridiano de Greenwich", "GMT"};
    String GMTBST[] = new String[] {"Fuso hor\u00e1rio do meridiano de Greenwich", "GMT",
                    "Fuso hor\u00e1rio de ver\u00e3o da Gr\u00e3-Bretanha", "BST"};
    String GST[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o do golfo", "GST",
                     "Hor\u00e1rio de luz natural do golfo", "GDT"};
    String HAST[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o do Hava\u00ed-Aleutian", "HAST",
                      "Hor\u00e1rio de luz natural do Hava\u00ed-Aleutian", "HADT"};
    String HKT[] =  new String[] {"Fuso hor\u00e1rio de Hong Kong", "HKT",
                      "Fuso hor\u00e1rio de ver\u00e3o de Hong Kong", "HKST"};
    String HST[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o do Hava\u00ed", "HST",
                     "Hor\u00e1rio de luz natural do Hava\u00ed", "HDT"};
    String ICT[] = new String[] {"Fuso hor\u00e1rio da Indochina", "ICT",
                     "Fuso hor\u00e1rio de ver\u00e3o da Indochina", "ICST"};
    String IRT[] = new String[] {"Fuso hor\u00e1rio do Ir\u00e3", "IRST",
                     "Hor\u00e1rio de luz natural do Ir\u00e3", "IRDT"};
    String ISRAEL[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o de Israel", "IST",
                    "Hor\u00e1rio de luz natural de Israel", "IDT"};
    String IST[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o da \u00cdndia", "IST",
                     "Hor\u00e1rio de luz natural da \u00cdndia", "IDT"};
    String JST[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o do Jap\u00e3o", "JST",
                     "Hor\u00e1rio de luz natural do Jap\u00e3o", "JDT"};
    String KST[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o da Coreia", "KST",
                     "Hor\u00e1rio de luz natural da Coreia", "KDT"};
    String LORD_HOWE[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o de Lord Howe", "LHST",
                       "Fuso hor\u00e1rio de ver\u00e3o de Lord Howe", "LHST"};
    String MHT[] = new String[] {"Fuso hor\u00e1rio das Ilhas Marshall", "MHT",
                     "Fuso hor\u00e1rio de ver\u00e3o das Ilhas Marshall", "MHST"};
    String MSK[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o de Moscou", "MSK",
                     "Hor\u00e1rio de luz natural de Moscou", "MSD"};
    String MST[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o das montanhas", "MST",
                     "Hor\u00e1rio de luz natural das montanhas", "MDT"};
    String MYT[] = new String[] {"Fuso hor\u00e1rio da Mal\u00e1sia", "MYT",
                     "Fuso hor\u00e1rio de ver\u00e3o da Mal\u00e1sia", "MYST"};
    String NORONHA[] = new String[] {"Fuso hor\u00e1rio de Fernando de Noronha", "FNT",
                     "Fuso hor\u00e1rio de ver\u00e3o de Fernando de Noronha", "FNST"};
    String NOVT[] = new String[] {"Fuso hor\u00e1rio de Novosibirsk", "NOVT",
                    "Fuso hor\u00e1rio de ver\u00e3o de Novosibirsk", "NOVST"};
        String NPT[] = new String[] {"Fuso hor\u00e1rio do Nepal", "NPT",
                                     "Fuso hor\u00e1rio de ver\u00e3o do Nepal", "NPST"};
    String NST[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o de Terra Nova", "NST",
                     "Hor\u00e1rio de luz natural de Terra Nova", "NDT"};
    String NZST[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o da Nova Zel\u00e2ndia", "NZST",
                      "Hor\u00e1rio de luz natural da Nova Zel\u00e2ndia", "NZDT"};
        String PITCAIRN[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o de Pitcairn", "PST",
                          "Hor\u00e1rio de luz natural de Pitcairn", "PDT"};
    String PKT[] = new String[] {"Fuso hor\u00e1rio do Paquist\u00e3o", "PKT",
                     "Fuso hor\u00e1rio de ver\u00e3o do Paquist\u00e3o", "PKST"};
    String PONT[] = new String[] {"Fuso hor\u00e1rio de Pohnpei", "PONT",
                      "Fuso hor\u00e1rio de ver\u00e3o de Pohnpei", "PONST"};
    String PST[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o do Pac\u00edfico", "PST",
                     "Hor\u00e1rio de luz natural do Pac\u00edfico", "PDT"};
        String RST[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o oriental", "EST",
                                     "Hor\u00e1rio de luz natural central", "CDT"};
    String SAST[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o da \u00c1frica do Sul", "SAST",
                      "Fuso hor\u00e1rio de ver\u00e3o da \u00c1frica do Sul", "SAST"};
    String SBT[] = new String[] {"Fuso hor\u00e1rio das Ilhas Salom\u00e3o", "SBT",
                     "Fuso hor\u00e1rio de ver\u00e3o das Ilhas Salom\u00e3o", "SBST"};
    String SGT[] = new String[] {"Fuso hor\u00e1rio de Cingapura", "SGT",
                     "Fuso hor\u00e1rio de ver\u00e1 de Cingapura", "SGST"};
    String SLST[] = new String[] {"Fuso hor\u00e1rio do meridiano de Greenwich", "GMT",
                      "Fuso hor\u00e1rio de ver\u00e3o de Serra Leoa", "SLST"};
    String TASMANIA[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o oriental (Tasm\u00e2nia)", "EST",
                      "Fuso hor\u00e1rio de ver\u00e3o oriental (Tasm\u00e2nia)", "EST"};
    String TMT[] = new String[] {"Fuso hor\u00e1rio do Turcomenist\u00e3o", "TMT",
                     "Fuso hor\u00e1rio de ver\u00e3o do Turcomenist\u00e3o", "TMST"};
    String TRUT[] = new String[] {"Fuso hor\u00e1rio de Chuuk", "CHUT",
                      "Fuso hor\u00e1rio de ver\u00e3o de Chuuk", "CHUST"};
    String ULAT[]= new String[] {"Fuso hor\u00e1rio de Ulan Bator", "ULAT",
                     "Fuso hor\u00e1rio de ver\u00e3o de Ulan Bator", "ULAST"};
    String WAT[] = new String[] {"Fuso hor\u00e1rio da \u00c1frica Ocidental", "WAT",
                     "Fuso hor\u00e1rio de ver\u00e3o da \u00c1frica Ocidental", "WAST"};
    String WET[] = new String[] {"Fuso hor\u00e1rio da Europa Ocidental", "WET",
                     "Fuso hor\u00e1rio de ver\u00e3o da Europa Ocidental", "WEST"};
    String WIT[] = new String[] {"Fuso hor\u00e1rio da Indon\u00e9sia Ocidental", "WIT",
                     "Fuso hor\u00e1rio de ver\u00e3o da Indon\u00e9sia Ocidental", "WIST"};
    String WST_AUS[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o ocidental (Austr\u00e1lia)", "WST",
                     "Fuso hor\u00e1rio de ver\u00e3o ocidental (Austr\u00e1lia)", "WST"};
    String SAMOA[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o de Samoa", "SST",
                       "Hor\u00e1rio de luz natural de Samoa", "SDT"};
    String WST_SAMOA[] = new String[] {"Fuso hor\u00e1rio de Samoa Ocidental", "WST",
                       "Fuso hor\u00e1rio de ver\u00e3o de Samoa Ocidental", "WSST"};
    String ChST[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o de Chamorro", "ChST",
                      "Hor\u00e1rio de luz natural de Chamorro", "ChDT"};
    String VICTORIA[] = new String[] {"Fuso hor\u00e1rio padr\u00e3o oriental (Victoria)", "EST",
                      "Fuso hor\u00e1rio de ver\u00e3o oriental (Victoria)", "EST"};
    String UTC[] = new String[] {"Tempo universal coordenado", "UTC",
                      "Tempo universal coordenado", "UTC"};
    String UZT[] = new String[] {"Fuso hor\u00e1rio do Uzbequist\u00e3o", "UZT",
                     "Fuso hor\u00e1rio de ver\u00e3o do Uzbequist\u00e3o", "UZST"};
    String WART[] = new String[] {"Fuso hor\u00e1rio da Argentina Ocidental", "WART",
                      "Fuso hor\u00e1rio de ver\u00e3o da Argentina Ocidental", "WARST"};


    return new Object[][] {
        {"America/Los_Angeles", PST},
        {"PST", PST},
        {"America/Denver", MST},
        {"MST", MST},
        {"America/Phoenix", MST},
        {"PNT", MST},
        {"America/Chicago", CST},
        {"CST", CST},
        {"America/New_York", EST},
        {"EST", EST},
        {"America/Indianapolis", EST},
        {"IET", EST},
        {"Pacific/Honolulu", HST},
        {"HST", HST},
        {"America/Anchorage", AKST},
        {"AST", AKST},
        {"America/Halifax", AST},
        {"America/St_Johns", NST},
        {"CNT", NST},
        {"Europe/Paris", CET},
        {"ECT", CET},
        {"GMT", GMT},
        {"Africa/Casablanca", WET},
        {"Asia/Jerusalem", ISRAEL},
        {"Asia/Tokyo", JST},
        {"JST", JST},
        {"Europe/Bucharest", EET},
        {"Asia/Shanghai", CTT},
        {"CTT", CTT},
        /* Don't change the order of the above zones
         * to keep compatibility with the previous version.
         */

        {"ACT", DARWIN},
        {"AET", EST_NSW},
        {"AGT", AGT},
        {"ART", EET},
        {"Africa/Abidjan", GMT},
        {"Africa/Accra", GHMT},
        {"Africa/Addis_Ababa", EAT},
        {"Africa/Algiers", CET},
        {"Africa/Asmara", EAT},
        {"Africa/Asmera", EAT},
        {"Africa/Bamako", GMT},
        {"Africa/Bangui", WAT},
        {"Africa/Banjul", GMT},
        {"Africa/Bissau", GMT},
        {"Africa/Blantyre", CAT},
        {"Africa/Brazzaville", WAT},
        {"Africa/Bujumbura", CAT},
        {"Africa/Cairo", EET},
        {"Africa/Ceuta", CET},
        {"Africa/Conakry", GMT},
        {"Africa/Dakar", GMT},
        {"Africa/Dar_es_Salaam", EAT},
        {"Africa/Djibouti", EAT},
        {"Africa/Douala", WAT},
        {"Africa/El_Aaiun", WET},
        {"Africa/Freetown", SLST},
        {"Africa/Gaborone", CAT},
        {"Africa/Harare", CAT},
        {"Africa/Johannesburg", SAST},
        {"Africa/Kampala", EAT},
        {"Africa/Khartoum", EAT},
        {"Africa/Kigali", CAT},
        {"Africa/Kinshasa", WAT},
        {"Africa/Lagos", WAT},
        {"Africa/Libreville", WAT},
        {"Africa/Lome", GMT},
        {"Africa/Luanda", WAT},
        {"Africa/Lubumbashi", CAT},
        {"Africa/Lusaka", CAT},
        {"Africa/Malabo", WAT},
        {"Africa/Maputo", CAT},
        {"Africa/Maseru", SAST},
        {"Africa/Mbabane", SAST},
        {"Africa/Mogadishu", EAT},
        {"Africa/Monrovia", GMT},
        {"Africa/Nairobi", EAT},
        {"Africa/Ndjamena", WAT},
        {"Africa/Niamey", WAT},
        {"Africa/Nouakchott", GMT},
        {"Africa/Ouagadougou", GMT},
        {"Africa/Porto-Novo", WAT},
        {"Africa/Sao_Tome", GMT},
        {"Africa/Timbuktu", GMT},
        {"Africa/Tripoli", EET},
        {"Africa/Tunis", CET},
        {"Africa/Windhoek", WAT},
        {"America/Adak", HAST},
        {"America/Anguilla", AST},
        {"America/Antigua", AST},
        {"America/Araguaina", BRT},
        {"America/Argentina/Buenos_Aires", AGT},
        {"America/Argentina/Catamarca", AGT},
        {"America/Argentina/ComodRivadavia", AGT},
        {"America/Argentina/Cordoba", AGT},
        {"America/Argentina/Jujuy", AGT},
        {"America/Argentina/La_Rioja", AGT},
        {"America/Argentina/Mendoza", AGT},
        {"America/Argentina/Rio_Gallegos", AGT},
        {"America/Argentina/Salta", AGT},
        {"America/Argentina/San_Juan", AGT},
        {"America/Argentina/San_Luis", WART},
        {"America/Argentina/Tucuman", AGT},
        {"America/Argentina/Ushuaia", AGT},
        {"America/Aruba", AST},
        {"America/Asuncion", new String[] {"Fuso hor\u00e1rio do Paraguai", "PYT",
                           "Fuso hor\u00e1rio de ver\u00e3o do Paraguai", "PYST"}},
            {"America/Atikokan", EST},
        {"America/Atka", HAST},
        {"America/Bahia", BRT},
        {"America/Bahia_Banderas", CST},
        {"America/Barbados", AST},
        {"America/Belem", BRT},
        {"America/Belize", CST},
            {"America/Blanc-Sablon", AST},
        {"America/Boa_Vista", AMT},
        {"America/Bogota", new String[] {"Fuso hor\u00e1rio da Col\u00f4mbia", "COT",
                         "Fuso hor\u00e1rio de ver\u00e3o da Col\u00f4mbia", "COST"}},
        {"America/Boise", MST},
        {"America/Buenos_Aires", AGT},
        {"America/Cambridge_Bay", MST},
        {"America/Campo_Grande", AMT},
        {"America/Cancun", CST},
        {"America/Caracas", new String[] {"Fuso hor\u00e1rio da Venezuela", "VET",
                          "Fuso hor\u00e1rio de ver\u00e3o da Venezuela", "VEST"}},
        {"America/Catamarca", AGT},
        {"America/Cayenne", new String[] {"Fuso hor\u00e1rio da Guiana Francesa", "GFT",
                          "Fuso hor\u00e1rio de ver\u00e3o da Guiana Francesa", "GFST"}},
        {"America/Cayman", EST},
        {"America/Chihuahua", MST},
        {"America/Coral_Harbour", EST},
        {"America/Cordoba", AGT},
        {"America/Costa_Rica", CST},
        {"America/Cuiaba", AMT},
        {"America/Curacao", AST},
        {"America/Danmarkshavn", GMT},
        {"America/Dawson", PST},
        {"America/Dawson_Creek", MST},
        {"America/Detroit", EST},
        {"America/Dominica", AST},
        {"America/Edmonton", MST},
        {"America/Eirunepe", AMT},
        {"America/El_Salvador", CST},
        {"America/Ensenada", PST},
        {"America/Fort_Wayne", EST},
        {"America/Fortaleza", BRT},
        {"America/Glace_Bay", AST},
        {"America/Godthab", new String[] {"Fuso hor\u00e1rio da Groenl\u00e2ndia Ocidental", "WGT",
                          "Fuso hor\u00e1rio de ver\u00e3o da Groenl\u00e2ndia Ocidental", "WGST"}},
        {"America/Goose_Bay", AST},
        {"America/Grand_Turk", EST},
        {"America/Grenada", AST},
        {"America/Guadeloupe", AST},
        {"America/Guatemala", CST},
        {"America/Guayaquil", new String[] {"Fuso hor\u00e1rio do Equador", "ECT",
                        "Fuso hor\u00e1rio de ver\u00e3o do Equador", "ECST"}},
        {"America/Guyana", new String[] {"Fuso hor\u00e1rio da Guiana", "GYT",
                         "Fuso hor\u00e1rio de ver\u00e3o da Guiana", "GYST"}},
        {"America/Havana", CUBA},
        {"America/Hermosillo", MST},
        {"America/Indiana/Indianapolis", EST},
        {"America/Indiana/Knox", CST},
        {"America/Indiana/Marengo", EST},
        {"America/Indiana/Petersburg", EST},
        {"America/Indiana/Tell_City", CST},
        {"America/Indiana/Vevay", EST},
        {"America/Indiana/Vincennes", EST},
        {"America/Indiana/Winamac", EST},
        {"America/Inuvik", MST},
        {"America/Iqaluit", EST},
        {"America/Jamaica", EST},
        {"America/Jujuy", AGT},
        {"America/Juneau", AKST},
        {"America/Kentucky/Louisville", EST},
        {"America/Kentucky/Monticello", EST},
        {"America/Knox_IN", CST},
        {"America/La_Paz", new String[] {"Fuso hor\u00e1rio da Bol\u00edvia", "BOT",
                         "Fuso hor\u00e1rio de ver\u00e3o da Bol\u00edvia", "BOST"}},
        {"America/Lima", new String[] {"Fuso hor\u00e1rio do Peru", "PET",
                       "Fuso hor\u00e1rio de ver\u00e3o do Peru", "PEST"}},
        {"America/Louisville", EST},
        {"America/Maceio", BRT},
        {"America/Managua", CST},
        {"America/Manaus", AMT},
        {"America/Marigot", AST},
        {"America/Martinique", AST},
        {"America/Mazatlan", MST},
        {"America/Mendoza", AGT},
        {"America/Menominee", CST},
        {"America/Merida", CST},
        {"America/Mexico_City", CST},
        {"America/Miquelon", new String[] {"Fuso hor\u00e1rio padr\u00e3o de S\u00e3o Pedro e Miquelon", "PMST",
                           "Hor\u00e1rio de luz natural de S\u00e3o Pedro e Miquelon", "PMDT"}},
        {"America/Moncton", AST},
        {"America/Montevideo", new String[] {"Fuso hor\u00e1rio do Uruguai", "UYT",
                         "Fuso hor\u00e1rio de ver\u00e3o do Uruguai", "UYST"}},
        {"America/Monterrey", CST},
        {"America/Montreal", EST},
        {"America/Montserrat", AST},
        {"America/Nassau", EST},
        {"America/Nipigon", EST},
        {"America/Nome", AKST},
        {"America/Noronha", NORONHA},
        {"America/North_Dakota/Center", CST},
            {"America/North_Dakota/New_Salem", CST},
        {"America/Panama", EST},
        {"America/Pangnirtung", EST},
        {"America/Paramaribo", new String[] {"Fuso hor\u00e1rio do Suriname", "SRT",
                         "Fuso hor\u00e1rio de ver\u00e3o do Suriname", "SRST"}},
        {"America/Port-au-Prince", EST},
        {"America/Port_of_Spain", AST},
        {"America/Porto_Acre", AMT},
        {"America/Porto_Velho", AMT},
        {"America/Puerto_Rico", AST},
        {"America/Rainy_River", CST},
        {"America/Rankin_Inlet", CST},
        {"America/Recife", BRT},
        {"America/Regina", CST},
        {"America/Resolute", RST},
        {"America/Rio_Branco", AMT},
        {"America/Rosario", AGT},
        {"America/Santarem", BRT},
        {"America/Santiago", CLT},
        {"America/Santo_Domingo", AST},
        {"America/Sao_Paulo", BRT},
        {"America/Scoresbysund", EGT},
        {"America/Shiprock", MST},
        {"America/St_Barthelemy", AST},
        {"America/St_Kitts", AST},
        {"America/St_Lucia", AST},
        {"America/St_Thomas", AST},
        {"America/St_Vincent", AST},
        {"America/Swift_Current", CST},
        {"America/Tegucigalpa", CST},
        {"America/Thule", AST},
        {"America/Thunder_Bay", EST},
        {"America/Tijuana", PST},
        {"America/Toronto", EST},
        {"America/Tortola", AST},
        {"America/Vancouver", PST},
        {"America/Virgin", AST},
        {"America/Whitehorse", PST},
        {"America/Winnipeg", CST},
        {"America/Yakutat", AKST},
        {"America/Yellowknife", MST},
        {"Antarctica/Casey", WST_AUS},
        {"Antarctica/Davis", new String[] {"Fuso hor\u00e1rio de Davis", "DAVT",
                           "Fuso hor\u00e1rio de ver\u00e3o de Davis", "DAVST"}},
        {"Antarctica/DumontDUrville", new String[] {"Fuso hor\u00e1rio de Dumont-d'Urville", "DDUT",
                            "Fuso hor\u00e1rio de ver\u00e3o de Dumont-d'Urville", "DDUST"}},
        {"Antarctica/Mawson", new String[] {"Fuso hor\u00e1rio de Mawson", "MAWT",
                        "Fuso hor\u00e1rio de ver\u00e3o de Mawson", "MAWST"}},
        {"Antarctica/McMurdo", NZST},
        {"Antarctica/Palmer", CLT},
        {"Antarctica/Rothera", new String[] {"Fuso hor\u00e1rio de Rothera", "ROTT",
                         "Fuso hor\u00e1rio de ver\u00e3o de Rothera", "ROTST"}},
        {"Antarctica/South_Pole", NZST},
        {"Antarctica/Syowa", new String[] {"Fuso hor\u00e1rio de Syowa", "SYOT",
                           "Fuso hor\u00e1rio de ver\u00e3o de Syowa", "SYOST"}},
        {"Antarctica/Vostok", new String[] {"Fuso hor\u00e1rio de Vostok", "VOST",
                        "Fuso hor\u00e1rio de ver\u00e3o de Vostok", "VOSST"}},
        {"Arctic/Longyearbyen", CET},
        {"Asia/Aden", ARAST},
        {"Asia/Almaty", new String[] {"Fuso hor\u00e1rio de Alma-Ata", "ALMT",
                      "Fuso hor\u00e1rio de ver\u00e3o de Alma-Ata", "ALMST"}},
        {"Asia/Amman", EET},
        {"Asia/Anadyr", new String[] {"Fuso hor\u00e1rio de Anadyr", "ANAT",
                      "Fuso hor\u00e1rio de ver\u00e3o de Anadyr", "ANAST"}},
        {"Asia/Aqtau", new String[] {"Fuso hor\u00e1rio de Aqtau", "AQTT",
                     "Fuso hor\u00e1rio de ver\u00e3o de Aqtau", "AQTST"}},
        {"Asia/Aqtobe", new String[] {"Fuso hor\u00e1rio de Aqtobe", "AQTT",
                      "Fuso hor\u00e1rio de ver\u00e3o de Aqtobe", "AQTST"}},
        {"Asia/Ashgabat", TMT},
        {"Asia/Ashkhabad", TMT},
        {"Asia/Baghdad", ARAST},
        {"Asia/Bahrain", ARAST},
        {"Asia/Baku", new String[] {"Fuso hor\u00e1rio do Azerbaij\u00e3o", "AZT",
                    "Fuso hor\u00e1rio de ver\u00e3o do Azerbaij\u00e3o", "AZST"}},
        {"Asia/Bangkok", ICT},
        {"Asia/Beirut", EET},
        {"Asia/Bishkek", new String[] {"Fuso hor\u00e1rio do Quirguist\u00e3o", "KGT",
                       "Fuso hor\u00e1rio de ver\u00e3o do Quirguist\u00e3o", "KGST"}},
        {"Asia/Brunei", new String[] {"Fuso hor\u00e1rio de Brunei", "BNT",
                      "Fuso hor\u00e1rio de ver\u00e3o de Brunei", "BNST"}},
        {"Asia/Calcutta", IST},
        {"Asia/Choibalsan", new String[] {"Fuso hor\u00e1rio de Choibalsan", "CHOT",
                          "Fuso hor\u00e1rio de ver\u00e3o de Choibalsan", "CHOST"}},
        {"Asia/Chongqing", CTT},
        {"Asia/Chungking", CTT},
        {"Asia/Colombo", IST},
        {"Asia/Dacca", BDT},
        {"Asia/Dhaka", BDT},
        {"Asia/Dili", new String[] {"Fuso hor\u00e1rio do Timor-Leste", "TLT",
                    "Fuso hor\u00e1rio de ver\u00e3o do Timor-Leste", "TLST"}},
        {"Asia/Damascus", EET},
        {"Asia/Dubai", GST},
        {"Asia/Dushanbe", new String[] {"Fuso hor\u00e1rio do Tadjiquist\u00e3o", "TJT",
                        "Fuso hor\u00e1rio de ver\u00e3o do Tadjiquist\u00e3o", "TJST"}},
        {"Asia/Gaza", EET},
        {"Asia/Harbin", CTT},
        {"Asia/Ho_Chi_Minh", ICT},
        {"Asia/Hong_Kong", HKT},
        {"Asia/Hovd", new String[] {"Fuso hor\u00e1rio de Hovd", "HOVT",
                    "Fuso hor\u00e1rio de ver\u00e3o de Hovd", "HOVST"}},
        {"Asia/Irkutsk", new String[] {"Fuso hor\u00e1rio de Irkutsk", "IRKT",
                       "Fuso hor\u00e1rio de ver\u00e3o de Irkutsk", "IRKST"}},
        {"Asia/Istanbul", EET},
        {"Asia/Jakarta", WIT},
        {"Asia/Jayapura", new String[] {"Fuso hor\u00e1rio da Indon\u00e9sia Oriental", "EIT",
                        "Fuso hor\u00e1rio de ver\u00e3o da Indon\u00e9sia Oriental", "EIST"}},
        {"Asia/Kabul", new String[] {"Fuso hor\u00e1rio do Afeganist\u00e3o", "AFT",
                     "Fuso hor\u00e1rio de ver\u00e3o do Afeganist\u00e3o", "AFST"}},
        {"Asia/Kamchatka", new String[] {"Fuso hor\u00e1rio de Petropavlovsk-Kamchatski", "PETT",
                         "Fuso hor\u00e1rio de ver\u00e3o de Petropavlovsk-Kamchatski", "PETST"}},
        {"Asia/Karachi", PKT},
        {"Asia/Kashgar", CTT},
        {"Asia/Kathmandu", NPT},
        {"Asia/Katmandu", NPT},
        {"Asia/Kolkata", IST},
        {"Asia/Krasnoyarsk", new String[] {"Fuso hor\u00e1rio de Krasnoyarsk", "KRAT",
                           "Fuso hor\u00e1rio de ver\u00e3o de Krasnoyarsk", "KRAST"}},
        {"Asia/Kuala_Lumpur", MYT},
        {"Asia/Kuching", MYT},
        {"Asia/Kuwait", ARAST},
        {"Asia/Macao", CTT},
        {"Asia/Macau", CTT},
        {"Asia/Magadan", new String[] {"Fuso hor\u00e1rio de Magadan", "MAGT",
                       "Fuso hor\u00e1rio de ver\u00e3o de Magadan", "MAGST"}},
        {"Asia/Makassar", CIT},
        {"Asia/Manila", new String[] {"Fuso hor\u00e1rio das Filipinas", "PHT",
                      "Fuso hor\u00e1rio de ver\u00e3o das Filipinas", "PHST"}},
        {"Asia/Muscat", GST},
        {"Asia/Nicosia", EET},
        {"Asia/Novokuznetsk", NOVT},
        {"Asia/Novosibirsk", NOVT},
        {"Asia/Oral", new String[] {"Fuso hor\u00e1rio de Uralsk", "ORAT",
                    "Fuso hor\u00e1rio de ver\u00e3o de Uralsk", "ORAST"}},
        {"Asia/Omsk", new String[] {"Fuso hor\u00e1rio de Omsk", "OMST",
                    "Fuso hor\u00e1rio de ver\u00e3o de Omsk", "OMSST"}},
        {"Asia/Phnom_Penh", ICT},
        {"Asia/Pontianak", WIT},
        {"Asia/Pyongyang", KST},
        {"Asia/Qatar", ARAST},
        {"Asia/Qyzylorda", new String[] {"Fuso hor\u00e1rio de Kizil-Orda", "QYZT",
                         "Fuso hor\u00e1rio de ver\u00e3o de Kizil-Orda", "QYZST"}},
        {"Asia/Rangoon", new String[] {"Fuso hor\u00e1rio de Mianmar", "MMT",
                       "Fuso hor\u00e1rio de ver\u00e3o de Mianmar", "MMST"}},
        {"Asia/Riyadh", ARAST},
        {"Asia/Saigon", ICT},
        {"Asia/Sakhalin", new String[] {"Fuso hor\u00e1rio de Sakhalina", "SAKT",
                        "Fuso hor\u00e1rio de ver\u00e3o de Sakhalina", "SAKST"}},
        {"Asia/Samarkand", UZT},
        {"Asia/Seoul", KST},
        {"Asia/Singapore", SGT},
        {"Asia/Taipei", CTT},
        {"Asia/Tel_Aviv", ISRAEL},
        {"Asia/Tashkent", UZT},
        {"Asia/Tbilisi", new String[] {"Fuso hor\u00e1rio da Ge\u00f3rgia", "GET",
                       "Fuso hor\u00e1rio de ver\u00e3o da Ge\u00f3rgia", "GEST"}},
        {"Asia/Tehran", IRT},
        {"Asia/Thimbu", BTT},
        {"Asia/Thimphu", BTT},
        {"Asia/Ujung_Pandang", CIT},
        {"Asia/Ulaanbaatar", ULAT},
        {"Asia/Ulan_Bator", ULAT},
        {"Asia/Urumqi", CTT},
        {"Asia/Vientiane", ICT},
        {"Asia/Vladivostok", new String[] {"Fuso hor\u00e1rio de Vladivostok", "VLAT",
                           "Fuso hor\u00e1rio de ver\u00e3o de Vladivostok", "VLAST"}},
        {"Asia/Yakutsk", new String[] {"Fuso hor\u00e1rio de Yakutsk", "YAKT",
                       "Fuso hor\u00e1rio de ver\u00e3o de Yakutsk", "YAKST"}},
        {"Asia/Yekaterinburg", new String[] {"Fuso hor\u00e1rio de Yekaterinburgo", "YEKT",
                         "Fuso hor\u00e1rio de ver\u00e3o de Yekaterinburgo", "YEKST"}},
        {"Asia/Yerevan", ARMT},
        {"Atlantic/Azores", new String[] {"Fuso hor\u00e1rio das A\u00e7ores", "AZOT",
                          "Fuso hor\u00e1rio de ver\u00e3o das A\u00e7ores", "AZOST"}},
        {"Atlantic/Bermuda", AST},
        {"Atlantic/Canary", WET},
        {"Atlantic/Cape_Verde", new String[] {"Fuso hor\u00e1rio de Cabo Verde", "CVT",
                          "Fuso hor\u00e1rio de ver\u00e3o de Cabo Verde", "CVST"}},
        {"Atlantic/Faeroe", WET},
        {"Atlantic/Faroe", WET},
        {"Atlantic/Jan_Mayen", CET},
        {"Atlantic/Madeira", WET},
        {"Atlantic/Reykjavik", GMT},
        {"Atlantic/South_Georgia", new String[] {"Fuso hor\u00e1rio padr\u00e3o da Ge\u00f3rgia do Sul", "GST",
                             "Hor\u00e1rio de luz natural da Ge\u00f3rgia do Sul", "GDT"}},
        {"Atlantic/St_Helena", GMT},
        {"Atlantic/Stanley", new String[] {"Fuso hor\u00e1rio das Ilhas Falkland", "FKT",
                           "Fuso hor\u00e1rio de ver\u00e3o das Ilhas Falkland", "FKST"}},
        {"Australia/ACT", EST_NSW},
        {"Australia/Adelaide", ADELAIDE},
        {"Australia/Brisbane", BRISBANE},
        {"Australia/Broken_Hill", BROKEN_HILL},
        {"Australia/Canberra", EST_NSW},
        {"Australia/Currie", EST_NSW},
        {"Australia/Darwin", DARWIN},
        {"Australia/Eucla", new String[] {"Fuso hor\u00e1rio ocidental central (Austr\u00e1lia)", "CWST",
                          "Fuso hor\u00e1rio de ver\u00e3o ocidental central (Austr\u00e1lia)", "CWST"}},
        {"Australia/Hobart", TASMANIA},
        {"Australia/LHI", LORD_HOWE},
        {"Australia/Lindeman", BRISBANE},
        {"Australia/Lord_Howe", LORD_HOWE},
        {"Australia/Melbourne", VICTORIA},
        {"Australia/North", DARWIN},
        {"Australia/NSW", EST_NSW},
        {"Australia/Perth", WST_AUS},
        {"Australia/Queensland", BRISBANE},
        {"Australia/South", ADELAIDE},
        {"Australia/Sydney", EST_NSW},
        {"Australia/Tasmania", TASMANIA},
        {"Australia/Victoria", VICTORIA},
        {"Australia/West", WST_AUS},
        {"Australia/Yancowinna", BROKEN_HILL},
        {"BET", BRT},
        {"BST", BDT},
        {"Brazil/Acre", AMT},
        {"Brazil/DeNoronha", NORONHA},
        {"Brazil/East", BRT},
        {"Brazil/West", AMT},
        {"Canada/Atlantic", AST},
        {"Canada/Central", CST},
        {"Canada/East-Saskatchewan", CST},
        {"Canada/Eastern", EST},
        {"Canada/Mountain", MST},
        {"Canada/Newfoundland", NST},
        {"Canada/Pacific", PST},
        {"Canada/Yukon", PST},
        {"Canada/Saskatchewan", CST},
        {"CAT", CAT},
        {"CET", CET},
        {"Chile/Continental", CLT},
        {"Chile/EasterIsland", EASTER},
        {"CST6CDT", CST},
        {"Cuba", CUBA},
        {"EAT", EAT},
        {"EET", EET},
        {"Egypt", EET},
        {"Eire", DUBLIN},
        {"EST5EDT", EST},
        {"Etc/Greenwich", GMT},
        {"Etc/UCT", UTC},
        {"Etc/Universal", UTC},
        {"Etc/UTC", UTC},
        {"Etc/Zulu", UTC},
        {"Europe/Amsterdam", CET},
        {"Europe/Andorra", CET},
        {"Europe/Athens", EET},
        {"Europe/Belfast", GMTBST},
        {"Europe/Belgrade", CET},
        {"Europe/Berlin", CET},
        {"Europe/Bratislava", CET},
        {"Europe/Brussels", CET},
        {"Europe/Budapest", CET},
        {"Europe/Chisinau", EET},
        {"Europe/Copenhagen", CET},
        {"Europe/Dublin", DUBLIN},
        {"Europe/Gibraltar", CET},
            {"Europe/Guernsey", GMTBST},
        {"Europe/Helsinki", EET},
            {"Europe/Isle_of_Man", GMTBST},
        {"Europe/Istanbul", EET},
            {"Europe/Jersey", GMTBST},
        {"Europe/Kaliningrad", EET},
        {"Europe/Kiev", EET},
        {"Europe/Lisbon", WET},
        {"Europe/Ljubljana", CET},
        {"Europe/London", GMTBST},
        {"Europe/Luxembourg", CET},
        {"Europe/Madrid", CET},
        {"Europe/Malta", CET},
        {"Europe/Mariehamn", EET},
        {"Europe/Minsk", EET},
        {"Europe/Monaco", CET},
        {"Europe/Moscow", MSK},
        {"Europe/Nicosia", EET},
        {"Europe/Oslo", CET},
        {"Europe/Podgorica", CET},
        {"Europe/Prague", CET},
        {"Europe/Riga", EET},
        {"Europe/Rome", CET},
        {"Europe/Samara", new String[] {"Fuso hor\u00e1rio de Samara", "SAMT",
                        "Fuso hor\u00e1rio de ver\u00e3o de Samara", "SAMST"}},
        {"Europe/San_Marino", CET},
        {"Europe/Sarajevo", CET},
        {"Europe/Simferopol", EET},
        {"Europe/Skopje", CET},
        {"Europe/Sofia", EET},
        {"Europe/Stockholm", CET},
        {"Europe/Tallinn", EET},
        {"Europe/Tirane", CET},
        {"Europe/Tiraspol", EET},
        {"Europe/Uzhgorod", EET},
        {"Europe/Vaduz", CET},
        {"Europe/Vatican", CET},
        {"Europe/Vienna", CET},
        {"Europe/Vilnius", EET},
            {"Europe/Volgograd", new String[] {"Fuso hor\u00e1rio de Volgogrado", "VOLT",
                                               "Fuso hor\u00e1rio de ver\u00e3o de Volgogrado", "VOLST"}},
        {"Europe/Warsaw", CET},
        {"Europe/Zagreb", CET},
        {"Europe/Zaporozhye", EET},
        {"Europe/Zurich", CET},
        {"GB", GMTBST},
        {"GB-Eire", GMTBST},
        {"Greenwich", GMT},
        {"Hongkong", HKT},
        {"Iceland", GMT},
        {"Iran", IRT},
        {"IST", IST},
        {"Indian/Antananarivo", EAT},
        {"Indian/Chagos", new String[] {"Fuso hor\u00e1rio dos territ\u00f3rios do Oceano \u00cdndico", "IOT",
                        "Fuso hor\u00e1rio de ver\u00e3o dos territ\u00f3rios do Oceano \u00cdndico", "IOST"}},
        {"Indian/Christmas", new String[] {"Fuso hor\u00e1rio das Ilhas Christmas", "CXT",
                           "Fuso hor\u00e1rio de ver\u00e3o das Ilhas Christmas", "CXST"}},
        {"Indian/Cocos", new String[] {"Fuso hor\u00e1rio das Ilhas Cocos", "CCT",
                       "Fuso hor\u00e1rio de ver\u00e3o das Ilhas Cocos", "CCST"}},
        {"Indian/Comoro", EAT},
        {"Indian/Kerguelen", new String[] {"Fuso hor\u00e1rio das Terras Austrais e Ant\u00e1rticas Francesas", "TFT",
                           "Fuso hor\u00e1rio de ver\u00e3o das Terras Austrais e Ant\u00e1rticas Francesas", "TFST"}},
        {"Indian/Mahe", new String[] {"Fuso hor\u00e1rio das Seychelles", "SCT",
                      "Fuso hor\u00e1rio de ver\u00e3o das Seychelles", "SCST"}},
        {"Indian/Maldives", new String[] {"Fuso hor\u00e1rio das Maldivas", "MVT",
                          "Fuso hor\u00e1rio de ver\u00e3o das Maldivas", "MVST"}},
        {"Indian/Mauritius", new String[] {"Fuso hor\u00e1rio das Ilhas Maur\u00edcio", "MUT",
                           "Fuso hor\u00e1rio de ver\u00e3o das Ilhas Maur\u00edcio", "MUST"}},
        {"Indian/Mayotte", EAT},
        {"Indian/Reunion", new String[] {"Fuso hor\u00e1rio de Reuni\u00e3o", "RET",
                         "Fuso hor\u00e1rio de ver\u00e3o de Reuni\u00e3o", "REST"}},
        {"Israel", ISRAEL},
        {"Jamaica", EST},
        {"Japan", JST},
        {"Kwajalein", MHT},
        {"Libya", EET},
        {"MET", new String[] {"Fuso hor\u00e1rio da Europa M\u00e9dia", "MET",
                  "Fuso hor\u00e1rio de ver\u00e3o da Europa M\u00e9dia", "MEST"}},
        {"Mexico/BajaNorte", PST},
        {"Mexico/BajaSur", MST},
        {"Mexico/General", CST},
        {"MIT", WST_SAMOA},
        {"MST7MDT", MST},
        {"Navajo", MST},
        {"NET", ARMT},
        {"NST", NZST},
        {"NZ", NZST},
        {"NZ-CHAT", CHAST},
        {"PLT", PKT},
        {"Portugal", WET},
        {"PRT", AST},
        {"Pacific/Apia", WST_SAMOA},
        {"Pacific/Auckland", NZST},
        {"Pacific/Chatham", CHAST},
        {"Pacific/Chuuk", TRUT},
        {"Pacific/Easter", EASTER},
        {"Pacific/Efate", new String[] {"Fuso hor\u00e1rio de Vanuatu", "VUT",
                        "Fuso hor\u00e1rio de ver\u00e3o de Vanuatu", "VUST"}},
        {"Pacific/Enderbury", new String[] {"Fuso hor\u00e1rio das Ilhas F\u00e9nix", "PHOT",
                        "Fuso hor\u00e1rio de ver\u00e3o das Ilhas F\u00e9nix", "PHOST"}},
        {"Pacific/Fakaofo", new String[] {"Fuso hor\u00e1rio de Tokelau", "TKT",
                          "Fuso hor\u00e1rio de ver\u00e3o de Tokelau", "TKST"}},
        {"Pacific/Fiji", new String[] {"Fuso hor\u00e1rio de Fiji", "FJT",
                       "Fuso hor\u00e1rio de ver\u00e3o de Fiji", "FJST"}},
        {"Pacific/Funafuti", new String[] {"Fuso hor\u00e1rio de Tuvalu", "TVT",
                           "Fuso hor\u00e1rio de ver\u00e3o de Tuvalu", "TVST"}},
        {"Pacific/Galapagos", new String[] {"Fuso hor\u00e1rio das Ilhas Gal\u00e1pagos", "GALT",
                        "Fuso hor\u00e1rio de ver\u00e3o das Ilhas Gal\u00e1pagos", "GALST"}},
        {"Pacific/Gambier", GAMBIER},
        {"Pacific/Guadalcanal", SBT},
        {"Pacific/Guam", ChST},
        {"Pacific/Johnston", HST},
        {"Pacific/Kiritimati", new String[] {"Fuso hor\u00e1rio das Esp\u00f3rades Equatoriais", "LINT",
                         "Fuso hor\u00e1rio de ver\u00e3o das Esp\u00f3rades Equatoriais", "LINST"}},
        {"Pacific/Kosrae", new String[] {"Fuso hor\u00e1rio de Kosrae", "KOST",
                         "Fuso hor\u00e1rio de ver\u00e3o de Kosrae", "KOSST"}},
        {"Pacific/Kwajalein", MHT},
        {"Pacific/Majuro", MHT},
        {"Pacific/Marquesas", new String[] {"Fuso hor\u00e1rio das Ilhas Marquesas", "MART",
                        "Fuso hor\u00e1rio de ver\u00e3o das Ilhas Marquesas", "MARST"}},
        {"Pacific/Midway", SAMOA},
        {"Pacific/Nauru", new String[] {"Fuso hor\u00e1rio de Nauru", "NRT",
                        "Fuso hor\u00e1rio de ver\u00e3o de Nauru", "NRST"}},
        {"Pacific/Niue", new String[] {"Fuso hor\u00e1rio de Niue", "NUT",
                       "Fuso hor\u00e1rio de ver\u00e3o de Niue", "NUST"}},
        {"Pacific/Norfolk", new String[] {"Fuso hor\u00e1rio da Ilha de Norfolk", "NFT",
                          "Fuso hor\u00e1rio de ver\u00e3o da Ilha de Norfolk", "NFST"}},
        {"Pacific/Noumea", new String[] {"Fuso hor\u00e1rio da Nova Caled\u00f4nia", "NCT",
                         "Fuso hor\u00e1rio de ver\u00e3o da Nova Caled\u00f4nia", "NCST"}},
        {"Pacific/Pago_Pago", SAMOA},
        {"Pacific/Palau", new String[] {"Fuso hor\u00e1rio de Palau", "PWT",
                        "Fuso hor\u00e1rio de ver\u00e3o de Palau", "PWST"}},
        {"Pacific/Pitcairn", PITCAIRN},
        {"Pacific/Pohnpei", PONT},
        {"Pacific/Ponape", PONT},
        {"Pacific/Port_Moresby", new String[] {"Fuso hor\u00e1rio de Papua-Nova Guin\u00e9", "PGT",
                           "Fuso hor\u00e1rio de ver\u00e3o de Papua-Nova Guin\u00e9", "PGST"}},
        {"Pacific/Rarotonga", new String[] {"Fuso hor\u00e1rio das Ilhas Cook", "CKT",
                        "Fuso hor\u00e1rio de ver\u00e3o das Ilhas Cook", "CKHST"}},
        {"Pacific/Saipan", ChST},
        {"Pacific/Samoa", SAMOA},
        {"Pacific/Tahiti", new String[] {"Fuso hor\u00e1rio do Taiti", "TAHT",
                         "Fuso hor\u00e1rio de ver\u00e3o do Taiti", "TAHST"}},
        {"Pacific/Tarawa", new String[] {"Fuso hor\u00e1rio das Ilhas Gilbert", "GILT",
                         "Fuso hor\u00e1rio de ver\u00e3o das Ilhas Gilbert", "GILST"}},
        {"Pacific/Tongatapu", new String[] {"Fuso hor\u00e1rio de Tonga", "TOT",
                        "Fuso hor\u00e1rio de ver\u00e3o de Tonga", "TOST"}},
        {"Pacific/Truk", TRUT},
        {"Pacific/Wake", new String[] {"Fuso hor\u00e1rio de Wake", "WAKT",
                       "Fuso hor\u00e1rio de ver\u00e3o de Wake", "WAKST"}},
        {"Pacific/Wallis", new String[] {"Fuso hor\u00e1rio de Wallis e Futuna", "WFT",
                         "Fuso hor\u00e1rio de ver\u00e3o de Wallis e Futuna", "WFST"}},
        {"Pacific/Yap", TRUT},
        {"Poland", CET},
        {"PRC", CTT},
        {"PST8PDT", PST},
        {"ROK", KST},
        {"Singapore", SGT},
        {"SST", SBT},
        {"SystemV/AST4", AST},
        {"SystemV/AST4ADT", AST},
        {"SystemV/CST6", CST},
        {"SystemV/CST6CDT", CST},
        {"SystemV/EST5", EST},
        {"SystemV/EST5EDT", EST},
        {"SystemV/HST10", HST},
        {"SystemV/MST7", MST},
        {"SystemV/MST7MDT", MST},
        {"SystemV/PST8", PST},
        {"SystemV/PST8PDT", PST},
        {"SystemV/YST9", AKST},
        {"SystemV/YST9YDT", AKST},
        {"Turkey", EET},
        {"UCT", UTC},
        {"Universal", UTC},
        {"US/Alaska", AKST},
        {"US/Aleutian", HAST},
        {"US/Arizona", MST},
        {"US/Central", CST},
        {"US/Eastern", EST},
        {"US/Hawaii", HST},
        {"US/Indiana-Starke", CST},
        {"US/East-Indiana", EST},
        {"US/Michigan", EST},
        {"US/Mountain", MST},
        {"US/Pacific", PST},
        {"US/Pacific-New", PST},
        {"US/Samoa", SAMOA},
        {"UTC", UTC},
        {"VST", ICT},
        {"W-SU", MSK},
        {"WET", WET},
        {"Zulu", UTC},
        };
    }
}


