'\" t
.\" Copyright (c) 1997, 2013, Oracle and/or its affiliates. All rights reserved.
.\" Title: jar
.\" Language: English
.\" Date: 2013年11月21日
.\" SectDesc: 基本ツール
.\" Software: JDK 8
.\" Arch: 汎用
.\"
.\" DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
.\"
.\" This code is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License version 2 only, as
.\" published by the Free Software Foundation.
.\"
.\" This code is distributed in the hope that it will be useful, but WITHOUT
.\" ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
.\" FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
.\" version 2 for more details (a copy is included in the LICENSE file that
.\" accompanied this code).
.\"
.\" You should have received a copy of the GNU General Public License version
.\" 2 along with this work; if not, write to the Free Software Foundation,
.\" Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.\" Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
.\" or visit www.oracle.com if you need additional information or have any
.\" questions.
.\"
.pl 99999
.TH "jar" "1" "2013年11月21日" "JDK 8" "基本ツール"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
jar \- Java Archive (JAR)ファイルを操作します。
.SH "概要"
JARファイルの作成
.sp
.if n \{\
.RS 4
.\}
.nf
\fIjar c\fR[\fIefmMnv0\fR] [\fIentrypoint\fR] [\fIjarfile\fR] [\fImanifest\fR] [\fI\-C\fR \fIdir\fR] \fIfile\fR \&.\&.\&. [\-J\fIoption\fR \&.\&.\&.] [@\fIarg\-file\fR \&.\&.\&.]
.fi
.if n \{\
.RE
.\}
JARファイルの更新
.sp
.if n \{\
.RS 4
.\}
.nf
\fIjar u\fR[\fIefmMnv0\fR] [\fIentrypoint\fR] [\fIjarfile\fR] [\fImanifest\fR] [\fI\-C\fR \fIdir\fR] \fIfile\fR \&.\&.\&. [\-J\fIoption\fR \&.\&.\&.] [@\fIarg\-file\fR \&.\&.\&.]
.fi
.if n \{\
.RE
.\}
JARファイルの抽出
.sp
.if n \{\
.RS 4
.\}
.nf
\fIjar\fR \fIx\fR[\fIvf\fR] [\fIjarfile\fR] \fIfile\fR \&.\&.\&. [\-J\fIoption\fR \&.\&.\&.] [@\fIarg\-file\fR \&.\&.\&.]
.fi
.if n \{\
.RE
.\}
JARファイルのコンテンツのリスト
.sp
.if n \{\
.RS 4
.\}
.nf
\fIjar\fR \fIt\fR[\fIvf\fR] [\fIjarfile\fR] \fIfile\fR \&.\&.\&. [\-J\fIoption\fR \&.\&.\&.] [@\fIarg\-file\fR \&.\&.\&.]
.fi
.if n \{\
.RE
.\}
JARファイルへの索引の追加
.sp
.if n \{\
.RS 4
.\}
.nf
\fIjar\fR \fIi\fR \fIjarfile\fR [\-J\fIoption\fR \&.\&.\&.] [@\fIarg\-file\fR \&.\&.\&.]
.fi
.if n \{\
.RE
.\}
.SH "説明"
.PP
\fIjar\fRコマンドは、ZIPおよびZLIB圧縮形式に基づく汎用のアーカイブおよび圧縮ツールです。ただし、\fIjar\fRコマンドは、主にいくつかのJavaアプレットやアプリケーションを単一のアーカイブにパッケージ化するように設計されました。アプレットやアプリケーションのコンポーネント(ファイル、イメージ、およびサウンド)が1つのアーカイブに結合されていると、Javaエージェント(ブラウザなど)は、それらのコンポーネントを1回のHTTPトランザクションでダウンロードすることができ、コンポーネントごとに新しい接続が不要になります。これにより、ダウンロード時間が大幅に短縮されます。また、\fIjar\fRコマンドはファイルの圧縮も行うため、ダウンロード時間がさらに短縮されます。また、\fIjar\fRコマンドによって、ファイル内の個々のエントリにアプレット作成者による署名を書き込めるため、配布元の認証が可能になります。JARファイルは、圧縮されているかどうかにかかわらず、クラス・パスのエントリとして使用できます。
.PP
\fIjar\fRコマンドの構文は、\fItar\fRコマンドの構文に似ています。必須の\fI操作の引数\fRの1つで定義された複数の操作モードがあります。他の引数は、操作の動作を変更する\fIオプション\fR、または操作を実行するために必要な\fIオペランド\fRを使用します。
.SH "操作の引数"
.PP
\fIjar\fRコマンドを使用する場合は、次の操作の引数のいずれかを指定して実行される操作を選択する必要があります。コマンドラインで他の1文字のオプションと混在させることができますが、通常、操作の引数は指定される最初の引数です。
.PP
c
.RS 4
新しいJARアーカイブを作成します。
.RE
.PP
i
.RS 4
JARアーカイブの索引情報を生成します。
.RE
.PP
t
.RS 4
JARアーカイブのコンテンツをリストします。
.RE
.PP
u
.RS 4
JARアーカイブを更新します。
.RE
.PP
x
.RS 4
JARアーカイブからファイルを抽出します。
.RE
.SH "オプション"
.PP
次のオプションを使用して、JARファイルを作成、更新、抽出または表示する方法をカスタマイズします。
.PP
e
.RS 4
\fIentrypoint\fRオペランドで指定されるクラスを、実行可能JARファイルにバンドルされるスタンドアロンJavaアプリケーションのエントリ・ポイントに設定します。このオプションを使用すると、マニフェスト・ファイル内の\fIMain\-Class\fR属性値が作成またはオーバーライドされます。\fIe\fRオプションは、JARファイルの作成時(\fIc\fR)または更新時(\fIu\fR)に使用できます。
.sp
たとえば、次のコマンドでは、\fIMain\&.jar\fRアーカイブが\fIMain\&.class\fRファイルとともに作成されますが、その際、マニフェスト内の\fIMain\-Class\fR属性値は\fIMain\fRに設定されます。
.sp
.if n \{\
.RS 4
.\}
.nf
jar cfe Main\&.jar Main Main\&.class
.fi
.if n \{\
.RE
.\}
Java Runtime Environment (JRE)は、次のコマンドを実行して、このアプリケーションを直接呼び出すことができます。
.sp
.if n \{\
.RS 4
.\}
.nf
java \-jar Main\&.jar
.fi
.if n \{\
.RE
.\}
あるパッケージ内にエントリ・ポイントのクラス名が含まれている場合、ドット(\&.)またはスラッシュ(/)のいずれかを区切り文字として使用できます。たとえば、\fIMain\&.class\fRが\fImydir\fRという名前のパッケージに含まれている場合、エントリ・ポイントは次のいずれかの方法で指定できます。
.sp
.if n \{\
.RS 4
.\}
.nf
jar \-cfe Main\&.jar mydir/Main mydir/Main\&.class
jar \-cfe Main\&.jar mydir\&.Main mydir/Main\&.class
.fi
.if n \{\
.RE
.\}
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.TS
allbox tab(:);
l.
T{
注意
特定のマニフェストにも\fIMain\-Class\fR属性が含まれている場合に\fIm\fRオプションと\fIe\fRオプションの両方を同時に指定すると、\fIMain\-Class\fRの指定があいまいになります。このあいまいさによってエラーが発生し、\fIjar\fRコマンドの作成や更新の操作が終了します。
T}
.TE
.sp 1
.sp .5v
.RE
.RE
.PP
f
.RS 4
\fIjarfile\fRオペランドで指定されたファイルを、作成(\fIc\fR)、更新(\fIu\fR)、抽出(\fIx\fR)または表示(\fIt\fR)されるJARファイルの名前に設定します。\fIf\fRオプションおよび\fIjarfile\fRオペランドを省略すると、\fIjar\fRコマンドに、\fIstdin\fRからのJARファイル名を受け入れるか(\fIx\fRおよび\fIt\fRの場合)、JARファイルを\fIstdout\fRに送信すること(\fIc\fRおよび\fIu\fRの場合)が指示されます。
.RE
.PP
m
.RS 4
(\fIMETA\-INF/MANIFEST\&.MF\fRのアーカイブにある)
\fIjar\fRコマンドのマニフェスト・ファイルの\fImanifest\fRオペランドで指定されたファイルから、属性の名前と値のペアを含めます。\fIjar\fRコマンドは、同じ名前のエントリがすでに存在する場合を除き、属性の名前と値をJARファイルに追加します。同じ名前のエントリがすでに存在する場合、\fIjar\fRコマンドは属性の値を更新します。\fIm\fRオプションは、JARファイルの作成時(\fIc\fR)または更新時(\fIu\fR)に使用できます。
.sp
デフォルトのマニフェスト・ファイルには含まれないマニフェストに、特別な目的の名前\-値の属性ペアを追加できます。たとえば、ベンダー情報、リリース情報、パッケージ・シーリングを指定する属性、またはJARにバンドルされたアプリケーションを実行可能にするための属性を追加できます。\fIm\fRオプションの使用例は、http://docs\&.oracle\&.com/javase/tutorial/deployment/jar/index\&.htmlにある
プログラムのパッケージ化に関する項を参照してください。
.RE
.PP
M
.RS 4
マニフェスト・ファイル・エントリを作成しない(\fIc\fRおよび\fIu\fRの場合)か、またはマニフェスト・ファイル・エントリが存在する場合は削除します(\fIu\fRの場合)。\fIM\fRオプションは、JARファイルの作成時(\fIc\fR)または更新時(\fIu\fR)に使用できます。
.RE
.PP
n
.RS 4
JARファイルの作成(\fIc\fR)時に、このオプションは、コンテンツがpack200(1)コマンドのパックおよびアンパック操作の影響を受けないようにアーカイブを正規化します。この正規化を使用しない場合、署名付きJARの署名は無効になります。
.RE
.PP
v
.RS 4
詳細な出力を標準出力に生成します。例を参照してください。
.RE
.PP
0
.RS 4
(ゼロ) ZIP圧縮を使用しないでJARファイルを作成(\fIc\fR)または更新(\fIu\fR)します。
.RE
.PP
\-C \fIdir\fR
.RS 4
JARファイルの作成(\fIc\fR)または更新(\fIu\fR)時に、このオプションは\fIfile\fRオペランドで指定されたファイルの処理中にディレクトリを一時的に変更します。この操作は、UNIX
\fItar\fRユーティリティの\fI\-C\fRオプションと同様になることを目的としています。たとえば、次のコマンドによって、\fIclasses\fRディレクトリに変更され、そのディレクトリから\fImy\&.jar\fRに\fIBar\&.class\fRファイルが追加されます。
.sp
.if n \{\
.RS 4
.\}
.nf
jar uf my\&.jar \-C classes Bar\&.class
.fi
.if n \{\
.RE
.\}
次のコマンドでは、\fIclasses\fRディレクトリに移動し、classesディレクトリ内のすべてのファイルを\fImy\&.jar\fRに追加します(JARファイルには\fIclasses\fRディレクトリを作成しません)。次に元のディレクトリに戻ってから、\fIbin\fRディレクトリに移動し、\fIXyz\&.class\fRを\fImy\&.jar\fRに追加します。
.sp
.if n \{\
.RS 4
.\}
.nf
jar uf my\&.jar \-C classes \&. \-C bin Xyz\&.class
.fi
.if n \{\
.RE
.\}
\fIclasses\fRに\fIbar1\fRファイルと\fIbar2\fRファイルが含まれている場合、前述のコマンドを実行した後、JARファイルには次のものが含まれます。
.sp
.if n \{\
.RS 4
.\}
.nf
% \fIjar tf my\&.jar\fR
META\-INF/
META\-INF/MANIFEST\&.MF
bar1
bar2
Xyz\&.class
.fi
.if n \{\
.RE
.\}
.RE
.PP
\-J\fIoption\fR
.RS 4
指定したJVMオプションを、JREがJARファイルを実行する際に使用するように設定します。JVMオプションは、java(1)コマンドのリファレンス・ページで説明されています。たとえば、\fI\-J\-Xms48m\fRと指定すると、スタートアップ・メモリーは48MBに設定されます。
.RE
.SH "オペランド"
.PP
次のオペランドは、\fIjar\fRコマンドで認識されます。
.PP
\fIfile\fR
.RS 4
JARファイルの作成(\fIc\fR)または更新(\fIu\fR)時に、\fIfile\fRオペランドは、アーカイブに追加する必要のあるファイルまたはディレクトリのパスと名前を定義します。JARファイルの抽出(\fIx\fR)またはコンテンツのリスト(\fIt\fR)時に、\fIfile\fRオペランドは抽出またはリストするファイルのパスと名前を定義します。少なくとも1つの有効なファイルまたはディレクトリを指定する必要があります。複数の\fIfile\fRオペランドを空白で区切ります。\fIentrypoint\fR、\fIjarfile\fRまたは\fImanifest\fRオペランドが使用される場合は、その後に\fIfile\fRオペランドを指定する必要があります。
.RE
.PP
\fIentrypoint\fR
.RS 4
JARファイルの作成(\fIc\fR)または更新(\fIu\fR)時に、\fIentrypoint\fRオペランドは、実行可能JARファイルにバンドルされているスタンドアロンJavaアプリケーションのエントリ・ポイントとなるクラスの名前を定義します。\fIe\fRオプションが存在する場合は\fIentrypoint\fRオペランドを指定する必要があります。
.RE
.PP
\fIjarfile\fR
.RS 4
作成(\fIc\fR)、更新(\fIu\fR)、抽出(\fIx\fR)または表示(\fIt\fR)するファイルの名前を定義します。\fIf\fRオプションが存在する場合は\fIjarfile\fRオペランドを指定する必要があります。\fIf\fRオプションおよび\fIjarfile\fRオペランドを省略すると、\fIjar\fRコマンドに、\fIstdin\fRからのJARファイル名を受け入れるか(\fIx\fRおよび\fIt\fRの場合)、JARファイルを\fIstdout\fRに送信すること(\fIc\fRおよび\fIu\fRの場合)が指示されます。
.sp
JARファイルを索引付け(\fIi\fR)する場合は、\fIf\fRオプションを指定しないで\fIjarfile\fRオペランドを指定します。
.RE
.PP
\fImanifest\fR
.RS 4
JARファイルの作成(\fIc\fR)または更新(\fIu\fR)時に、\fImanifest\fRオペランドはJARファイルの\fIMANIFEST\&.MF\fRに含める属性の名前と値を持つ既存のマニフェスト・ファイルを定義します。\fIf\fRオプションが存在する場合は\fImanifest\fRオペランドを指定する必要があります。
.RE
.PP
\fI@arg\-file\fR
.RS 4
\fIjar\fRコマンドを短縮または簡素化するには、別のテキスト・ファイル内の引数を指定し、接頭辞としてアットマーク(@)を付けて\fIjar\fRコマンドに渡すことができます。\fIjar\fRコマンドは、アットマーク文字で始まる引数を見つけると、そのファイルの内容を展開して引数リストに挿入します。
.sp
引数ファイルには、\fIjar\fRコマンドのオプションと引数(引数ファイルをサポートしない起動ツールに渡される\fI\-J\fRオプションを除く)を含めることができます。ファイル内の引数は、空白または改行文字で区切ることができます。引数ファイル内のファイル名は、\fIjar\fRコマンドを実行できる現在のディレクトリに対して相対的であり、引数ファイルの場所に対しては相対的ではありません。通常はオペレーティング・システム・シェルによって展開されるアスタリスク(*)などのワイルドカードは展開されません。
.sp
次の例は、\fIfind\fRコマンドによる現在のディレクトリ出力からのファイル名で\fIclasses\&.list\fRファイルを作成する方法を示します。
.sp
.if n \{\
.RS 4
.\}
.nf
find \&. \-name \*(Aq*\&.class\*(Aq \-print > classes\&.list
.fi
.if n \{\
.RE
.\}
\fIjar\fRコマンドを実行し、\fI@arg\-file\fR構文を使用して\fIclasses\&.list\fRファイルを渡すことができます。
.sp
.if n \{\
.RS 4
.\}
.nf
jar cf my\&.jar @classes\&.list
.fi
.if n \{\
.RE
.\}
引数ファイルはパスを指定できますが、相対パスが記述された引数ファイル内のすべてのファイル名は、渡されたパスに対して相対的ではなく、\fIjar\fRコマンドの現在の作業ディレクトリに相対的となります。たとえば、次のようになります。
.sp
.if n \{\
.RS 4
.\}
.nf
jar @dir/classes\&.list
.fi
.if n \{\
.RE
.\}
.RE
.SH "注意"
.PP
\fIe\fR、\fIf\fRおよび\fIm\fRオプションは、\fIentrypoint\fR、\fIjarfile\fRおよび\fImanifest\fRオペランドと同じ順序でコマンドラインに出現する必要があります。
.sp
.if n \{\
.RS 4
.\}
.nf
jar cmef myManifestFile MyMainClass myFile\&.jar *\&.class
.fi
.if n \{\
.RE
.\}
.SH "例"
.PP
\fBExample 1\fR, 冗長な出力による現在のディレクトリからのすべてのファイルの追加
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
% ls
1\&.au          Animator\&.class    monkey\&.jpg
2\&.au          Wave\&.class        spacemusic\&.au
3\&.au          at_work\&.gif

% jar cvf bundle\&.jar *
added manifest
adding: 1\&.au(in = 2324) (out= 67)(deflated 97%)
adding: 2\&.au(in = 6970) (out= 90)(deflated 98%)
adding: 3\&.au(in = 11616) (out= 108)(deflated 99%)
adding: Animator\&.class(in = 2266) (out= 66)(deflated 97%)
adding: Wave\&.class(in = 3778) (out= 81)(deflated 97%)
adding: at_work\&.gif(in = 6621) (out= 89)(deflated 98%)
adding: monkey\&.jpg(in = 7667) (out= 91)(deflated 98%)
adding: spacemusic\&.au(in = 3079) (out= 73)(deflated 97%)
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBExample 2\fR, サブディレクトリからのファイルの追加
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
% ls \-F
audio/ classes/ images/
% jar cvf bundle\&.jar audio classes images
added manifest
adding: audio/(in = 0) (out= 0)(stored 0%)
adding: audio/1\&.au(in = 2324) (out= 67)(deflated 97%)
adding: audio/2\&.au(in = 6970) (out= 90)(deflated 98%)
adding: audio/3\&.au(in = 11616) (out= 108)(deflated 99%)
adding: audio/spacemusic\&.au(in = 3079) (out= 73)(deflated 97%)
adding: classes/(in = 0) (out= 0)(stored 0%)
adding: classes/Animator\&.class(in = 2266) (out= 66)(deflated 97%)
adding: classes/Wave\&.class(in = 3778) (out= 81)(deflated 97%)
adding: images/(in = 0) (out= 0)(stored 0%)
adding: images/monkey\&.jpg(in = 7667) (out= 91)(deflated 98%)
adding: images/at_work\&.gif(in = 6621) (out= 89)(deflated 98%)

% ls \-F
audio/ bundle\&.jar classes/ images/
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBExample 3\fR, JARのコンテンツのリスト
.RS 4
.sp
.if n \{\
.RS 4
.\}
.nf
% jar tf bundle\&.jar
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
META\-INF/
META\-INF/MANIFEST\&.MF
audio/1\&.au
audio/2\&.au
audio/3\&.au
audio/spacemusic\&.au
classes/Animator\&.class
classes/Wave\&.class
images/monkey\&.jpg
images/at_work\&.gif
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBExample 4\fR, 索引の追加
.RS 4
株式取引のアプリケーションの相互依存クラスを、\fImain\&.jar\fR、\fIbuy\&.jar\fRおよび\fIsell\&.jar\fRの3つのJARファイルに分割する場合、\fIi\fRオプションを使用します。\fImain\&.jar\fRマニフェスト内の\fIClass\-Path\fR属性を指定する場合、\fIi\fRオプションを使用して、アプリケーションのクラス・ロードの速度を向上できます。
.sp
.if n \{\
.RS 4
.\}
.nf
Class\-Path: buy\&.jar sell\&.jar
jar i main\&.jar
.fi
.if n \{\
.RE
.\}
\fIINDEX\&.LIST\fRファイルが\fIMETA\-INF\fRディレクトリに挿入されます。これにより、アプリケーションのクラス・ローダーによってクラスまたはリソースの検索が行われるときに、指定したJARファイルがダウンロードされるようになります。
.sp
アプリケーションのクラス・ローダーは、このファイルに格納されている情報を使用して、効率的にクラスをロードします。ディレクトリをコピーするには、最初に\fIdir1\fR内のファイルを\fIstdout\fRに圧縮してから、\fIstdin\fRから\fIdir2\fRにパイプラインを作成して抽出します(\fI\-f\fRオプションは両方の\fIjar\fRコマンドで省略します)。
.sp
.if n \{\
.RS 4
.\}
.nf
(cd dir1; jar c \&.) | (cd dir2; jar x)
.fi
.if n \{\
.RE
.\}
.RE
.SH "関連項目"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
pack200(1)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
http://docs\&.oracle\&.com/javase/tutorial/deployment/jar/index\&.htmlにある
JavaチュートリアルのJARに関する項
.RE
.br
'pl 8.5i
'bp
