." Copyright (c) 2004, 2011, Oracle and/or its affiliates. All rights reserved.
." DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
."
." This code is free software; you can redistribute it and/or modify it
." under the terms of the GNU General Public License version 2 only, as
." published by the Free Software Foundation.
."
." This code is distributed in the hope that it will be useful, but WITHOUT
." ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
." FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
." version 2 for more details (a copy is included in the LICENSE file that
." accompanied this code).
."
." You should have received a copy of the GNU General Public License version
." 2 along with this work; if not, write to the Free Software Foundation,
." Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
."
." Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
." or visit www.oracle.com if you need additional information or have any
." questions.
."
.TH jps 1 "07 May 2011"

.LP
.SH "名前"
jps \- Java 仮想マシンプロセスステータスツール
.LP
.RS 3
.TP 2
o
形式 
.TP 2
o
パラメータ 
.TP 2
o
説明 
.TP 2
o
オプション 
.TP 2
o
ホスト識別子 
.TP 2
o
出力形式 
.TP 2
o
例 
.TP 2
o
関連項目 
.RE

.LP
.SH "形式"
.LP
.nf
\f3
.fl
\fP\f3jps\fP [ \f2options\fP ] [ \f2hostid\fP ]
.br

.fl
.fi

.LP
.SH "パラメータ"
.LP
.RS 3
.TP 3
options 
コマンド行オプション。 
.TP 3
hostid 
プロセスレポートを生成するホストのホスト識別子。\f2hostid\fP には、通信プロトコル、ポート番号、実装に固有な他のデータを指定したオプションコンポーネントを含めることができます。 
.RE

.LP
.SH " 説明"
.LP
.LP
\f3jps\fP ツールは、ターゲットシステム上で計測された HotSpot Java 仮想マシン (JVM) を一覧表示します。このツールで表示できるレポート情報は、アクセス権を持った JVM に関するものに限定されます。
.LP
.LP
\f2hostid\fP を指定せずに \f3jps\fP を実行した場合、ローカルホストで計測された JVM が検索されます。\f2hostid\fP を指定して起動した場合、指定されたプロトコルとポートを使用して、指定されたホスト上の JVM を検索します。\f3jstatd\fP プロセスがターゲットホスト上で実行されていると想定されます。
.LP
.LP
\f3jps\fP コマンドは、ターゲットシステムで計測された各 JVM について、ローカル VM 識別子、つまり \f2lvmid\fP をレポートします。\f3lvmid\fP は、必須ではありませんが、一般的には JVM プロセスに対するオペレーティングシステムのプロセス識別子です。オプションを指定しない場合、\f3jps\fP によって、各 Java アプリケーションの \f2lvmid\fP が一覧表示され、それぞれにアプリケーションのクラス名または JAR ファイル名が簡単な形式で示されます。この簡単な形式のクラス名と JAR ファイル名では、クラスのパッケージ情報または JAR ファイルパス情報が省略されています。
.LP
.LP
\f3jps\fP コマンドは、\f3Java\fP 起動ツールを使用して \f2main\fP メソッドに渡されるクラス名と引数を検索します。独自の起動ツールを使用してターゲット JVM を起動した場合は、 \f2main\fP メソッドに渡されるクラス名 (または JAR ファイル名) と引数は利用できません。この場合、\f3jps\fP コマンドは、main メソッドへ渡されるクラス名 (または JAR ファイル名) と引数に対して、文字列 \f2Unknown\fP を出力します。
.LP
.LP
\f3jps\fP コマンドで生成される JVM のリストは、このコマンドを実行する主体に与えられたアクセス権に基づき、制限される場合があります。このコマンドは、オペレーティングシステム独自のアクセス制御機構による決定に基づいて、主体にアクセス権が与えられている JVM だけを一覧表示します。
.LP
.LP
\f3注:\fP このユーティリティーはサポート対象外であり、将来の JDK のバージョンでは利用できなくなる可能性があります。現在、Windows 98 および Windows Me プラットフォームでは使用できません。
.LP
.SH "オプション"
.LP
.LP
\f3jps\fP コマンドでは、コマンドの出力を変更するオプションが多数サポートされています。将来、これらのオプションは、変更または廃止される可能性があります。
.LP
.RS 3
.TP 3
\-q 
クラス名、JAR ファイル名、および \f2main\fP メソッドに渡された引数の出力を抑制し、ローカル VM 識別子の一覧のみを生成します。 
.TP 3
\-m 
main メソッドに渡される引数を出力します。この出力は、組み込まれている JVM に対して null になることもあります。  
.TP 3
\-l 
アプリケーションの主要なクラスのフルパッケージ名、またはアプリケーションの JAR ファイルへのフルパス名を出力します。 
.TP 3
\-v 
JVM に渡される引数を出力します。 
.TP 3
\-V 
フラグファイル (.hotspotrc ファイルまたは \-XX:Flags=<\f2filename\fP> の引数で指定されたファイル) を通じて JVM に渡される引数を出力します。 
.TP 3
\-Joption 
\f3jps\fP が呼び出す \f3java\fP 起動ツールに、\f2option\fP を渡します。たとえば、\f3\-J\-Xms48m\fP と指定すると、スタートアップメモリーは 48M バイトに設定されます。\f3\-J\fP を使って、Java で記述されたアプリケーションを実行する背後の VM にオプション渡すことは、よく行われています。 
.RE

.LP
.SS 
ホスト識別子
.LP
.LP
ホスト識別子、つまり \f2hostid\fP は、ターゲットシステムを示す文字列です。\f2hostid\fP 文字列の構文の大部分は、URI の構文に対応しています。
.LP
.nf
\f3
.fl
[\fP\f4protocol\fP\f3:][[//]\fP\f4hostname\fP\f3][:\fP\f4port\fP\f3][/\fP\f4servername\fP\f3]\fP
.br
\f3
.fl
\fP
.fi

.LP
.RS 3
.TP 3
protocol 
通信プロトコルです。\f2protocol\fP が省略され、\f2hostname\fP が指定されていない場合、デフォルトのプロトコルが、プラットフォーム固有の最適化されたローカルプロトコルになります。\f2protocol\fP が省略され、\f2hostname\fP が指定されている場合は、デフォルトプロトコルは \f3rmi\fP になります。 
.TP 3
hostname 
ターゲットホストを示すホスト名または IP アドレスです。\f2hostname\fP が省略されている場合は、ターゲットホストはローカルホストになります。 
.TP 3
port 
リモートサーバーと通信するためのデフォルトポートです。\f2hostname\fP が省略されているか、\f2protocol\fP で最適化されたローカルプロトコルが指定されている場合、\f2port\fP は無視されます。そうでなければ、\f2port\fP パラメータの扱いは、実装によって異なります。デフォルトの \f3rmi\fP プロトコルの場合、\f2port\fP は、リモートホスト上の rmiregistry のポート番号を示します。\f2port\fP が省略され、\f2protocol\fP で \f3rmi\fP が指定されている場合、デフォルトの rmiregistry ポート (1099) が使用されます。 
.TP 3
servername 
このパラメータの扱いは、実装によって異なります。最適化されたローカルプロトコルの場合、このフィールドは無視されます。\f3rmi\fP プロトコルの場合、このパラメータは、リモートホスト上の RMI リモートオブジェクトの名前を示す文字列になります。jstatd(1) コマンドについては、\f3\-n\fP オプションを参照してください。 
.RE

.LP
.SH "出力形式"
.LP
.LP
\f3jps\fP コマンドの出力は、次のパターンに従います。
.LP
.nf
\f3
.fl
\fP\f4lvmid\fP\f3 [ [ \fP\f4classname\fP\f3 | \fP\f4JARfilename\fP\f3 | "Unknown"] [ \fP\f4arg\fP\f3* ] [ \fP\f4jvmarg\fP\f3* ] ]\fP
.br
\f3
.fl
\fP
.fi

.LP
.LP
すべての出力トークンは空白で区切ります。\f2arg\fP の中で空白を使用すると、実際の定位置パラメータに引数をマッピングしようとするときに、あいまいになります。
.br
.br
\f3注\fP: 将来のリリースでこの形式は変更される可能性があるため、\f3jps\fP の出力を解析するスクリプトは作成しないことをお勧めします。\f3jps\fP 出力を解析するスクリプトを作成すると、このツールの将来のリリースで、作成したスクリプトを変更する必要が予測されます。
.br

.LP
.SH "例"
.LP
.LP
この節では、\f3jps\fP コマンドの例を示します。
.LP
.LP
ローカルホスト上で計測された JVM を一覧表示する場合:
.LP
.nf
\f3
.fl
\fP\f3jps\fP
.br

.fl
18027 Java2Demo.JAR
.br

.fl
18032 jps
.br

.fl
18005 jstat
.br

.fl
.fi

.LP
.LP
リモートホスト上で計測された JVM を一覧表示する場合:
.LP
.LP
この例では、\f3jstat\fP サーバーと、その内部 RMI レジストリまたは別の外部 \f3rmiregistry\fP プロセスのいずれかとが、リモートホストのデフォルトポート (ポート 1099) で実行されていると想定しています。また、ローカルホストが、リモートホストへの有効なアクセス権を持っていることも想定しています。この例には、\f2\-l\fP オプションも含まれ、クラス名または JAR ファイル名を詳細な形式で出力します。
.LP
.nf
\f3
.fl
\fP\f3jps \-l remote.domain\fP
.br

.fl
3002 /opt/jdk1.7.0/demo/jfc/Java2D/Java2Demo.JAR
.br

.fl
2857 sun.tools.jstatd.jstatd
.br

.fl
.fi

.LP
.LP
RMI レジストリにデフォルトではないポートを使用して、リモートホスト上で計測された JVM を一覧表示する場合:
.LP
.LP
この例では、内部 RMI レジストリがポート 2002 にバインドされた \f3jstatd\fP サーバーが、リモートホスト上で実行していると想定しています。また、\f2\-m\fP オプションを使用して、一覧表示されたそれぞれの Java アプリケーションの \f2main\fP メソッドに渡される引数を組み込んでいます。
.LP
.nf
\f3
.fl
\fP\f3jps \-m remote.domain:2002\fP
.br

.fl
3002 /opt/jdk1.7.0/demo/jfc/Java2D/Java2Demo.JAR
.br

.fl
3102 sun.tools.jstatd.jstatd \-p 2002
.fl
.fi

.LP
.SH "関連項目"
.LP
.RS 3
.TP 2
o
「java(1) \- Java アプリケーション起動ツール」 
.TP 2
o
「jstat(1) \- Java 仮想マシン統計データ監視ツール」 
.TP 2
o
「jstatd(1) \- 仮想マシン jstat デーモン」 
.TP 2
o
「rmiregistry(1) \- Java リモートオブジェクトレジストリ」 
.RE

.LP
 
