suite: Maxjdoc
tests:
- name: build
  tags:
    - daily
  commands:
    - cd make && ant build
  sharedEnviroment:
      MAXJDOC: ${MAXTEST_ROOT}/${BUILD_TAG}/maxjdoc
  clusterParameters:
    cpus: 1.0
    mem: 1024.0
    centos6: 1.0
