." Copyright (c) 1997, 2010, Oracle and/or its affiliates. All rights reserved.
." DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
."
." This code is free software; you can redistribute it and/or modify it
." under the terms of the GNU General Public License version 2 only, as
." published by the Free Software Foundation.
."
." This code is distributed in the hope that it will be useful, but WITHOUT
." ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
." FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
." version 2 for more details (a copy is included in the LICENSE file that
." accompanied this code).
."
." You should have received a copy of the GNU General Public License version
." 2 along with this work; if not, write to the Free Software Foundation,
." Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
."
." Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
." or visit www.oracle.com if you need additional information or have any
." questions.
."
.TH serialver 1 "02 Jun 2010"

.LP
.SH "名前"
serialver \- シリアルバージョンコマンド
.LP
.RS 3

.LP
.LP
\f3serialver\fP コマンドは \f2serialVersionUID\fP を返します。
.LP
.RE
.SH "形式"
.LP

.LP
.nf
\f3
.fl
\fP\f3serialver\fP [ options ] [ classnames ]
.fl
.fi

.LP
.RS 3

.LP
.RS 3
.TP 3
options 
このドキュメントで説明されているコマンド行オプションです。 
.TP 3
classnames 
1 つ以上のクラス名です。 
.RE

.LP
.RE
.SH "説明"
.LP

.LP
.LP
\f3serialver\fP は、1 つ以上のクラスの \f2serialVersionUID\fP を、展開しているクラスへコピーするのに適した形式で返します。引数を指定しないで呼び出すと、使用方法が表示されます。
.LP
.SH "オプション"
.LP

.LP
.RS 3
.TP 3
\-classpath <: で区切られたディレクトリと zip や jar ファイル> 
アプリケーションのクラスおよびリソースの検索パスを設定します。 
.RE

.LP
.RS 3
.TP 3
\-show 
簡単なユーザーインタフェースを表示します。完全指定のクラス名を入力して、Enter キーか [Show] ボタンを押し、シリアルバージョン UID を表示します。 
.TP 3
\-Joption 
Java 仮想マシンに \f2option\fP を渡します。 \f2option\fP には、java(1)のリファレンスページに記載されているオプションを 1 つ指定します。たとえば、\f3\-J\-Xms48m\fP と指定すると、スタートアップメモリーは 48M バイトに設定されます。 
.RE

.LP
.SH "注"
.LP

.LP
.LP
\f3serialver\fP コマンドは、指定されたクラスをその仮想マシン内に読み込んで初期化しますが、デフォルトではセキュリティーマネージャーの設定は行いません。信頼できないクラスとともに \f3serialver\fP を実行する場合には、次のオプションを使ってセキュリティーマネージャーを設定できます。
.LP
.RS 3

.LP
.LP
\f2\-J\-Djava.security.manager\fP
.LP
.RE
.LP
また、必要であれば、次のオプションを使ってセキュリティーポリシーを指定できます。
.LP
.RS 3

.LP
.LP
\f2\-J\-Djava.security.policy=<policy file>\fP
.LP
.RE
.SH "関連項目"
.LP

.LP
.LP
.na
\f2java.io.ObjectStreamClass\fP @
.fi
http://java.sun.com/javase/6/docs/api/java/io/ObjectStreamClass.html
.LP
 
