#
# Copyright (c) 2025, Oracle and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
#

set java [lrange $argv 0 end]

eval spawn $java

# Console::readLine()
send "abc\r"
expect {
    "ABC" { send_error "Console::readLine() received\n" }
    timeout {
        send_error "Error: Console::readLine() not received\n"
        exit 1
    }
}

# Console::readPassword()
send "def\r"
expect {
    "DEF" { send_error "Console::readPassword() received\n" }
    timeout {
        send_error "Error: Console::readPassword() not received\n"
        exit 1
    }
}

# Console::reader()
send "ghi\r"
expect {
    "GHI" { send_error "Console::reader() received\n" }
    timeout {
        send_error "Error: Console::reader() not received\n"
        exit 1
    }
}

# should receive eof
send "\r"
expect eof

# success
exit 0
