/*
 * Copyright (c) 2001, 2023, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

/*
 * This source code is provided to illustrate the usage of a given feature
 * or technique and has been deliberately simplified. Additional steps
 * required for a production-quality application, such as security checks,
 * input validation and proper error handling, might not be present in
 * this sample code.
 */


package com.sun.tools.example.debug.tty;

/**
 * <p> This class represents the <code>ResourceBundle</code>
 * for the following package(s):
 *
 * <ol>
 * <li> com.sun.tools.example.debug.tty
 * </ol>
 *
 */
public class TTYResources_ja extends java.util.ListResourceBundle {


    /**
     * Returns the contents of this <code>ResourceBundle</code>.
     *
     * <p>
     *
     * @return the contents of this <code>ResourceBundle</code>.
     */
    @Override
    public Object[][] getContents() {
        Object[][] temp = new Object[][] {
        // NOTE: The value strings in this file containing "{0}" are
        //       processed by the java.text.MessageFormat class.  Any
        //       single quotes appearing in these strings need to be
        //       doubled up.
        //
        // LOCALIZE THIS
        {"** classes list **", "** クラス・リスト **\n{0}"},
        {"** fields list **", "** フィールド・リスト **\n{0}"},
        {"** methods list **", "** メソッド・リスト **\n{0}"},
        {"*** Reading commands from", "*** {0}からのコマンドの読取り"},
        {"All threads resumed.", "すべてのスレッドが再開されました。"},
        {"All threads suspended.", "すべてのスレッドが中断されました。"},
        {"Argument is not defined for connector:", "引数{0}はコネクタに対して定義されていません: {1}"},
        {"Arguments match no method", "引数が適合するメソッドがありません"},
        {"Array:", "配列: {0}"},
        {"Array element is not a method", "配列要素はメソッドではありません"},
        {"Array index must be a integer type", "配列の添え字は整数型である必要があります"},
        {"base directory:", "ベース・ディレクトリ: {0}"},
        {"Breakpoint hit:", "ヒットしたブレークポイント: "},
        {"breakpoint", "ブレークポイント{0}"},
        {"Breakpoints set:", "設定されているブレークポイント:"},
        {"Breakpoints can be located only in classes.", "ブレークポイントはクラス内にのみ配置できます。{0}はインタフェースまたは配列です。"},
        {"Can only trace", "'methods'、'method exit'または'method exits'のみトレースできます"},
        {"cannot redefine existing connection", "{0}は既存の接続を再定義できません"},
        {"Cannot assign to a method invocation", "メソッド呼出しに割当てできません"},
        {"Cannot specify command line with connector:", "コネクタでコマンドラインを指定できません: {0}"},
        {"Cannot specify target vm arguments with connector:", "コネクタでターゲットVM引数を指定できません: {0}"},
        {"Class containing field must be specified.", "フィールドを含むクラスを指定する必要があります。"},
        {"Class:", "クラス: {0}"},
        {"Classic VM no longer supported.", "Classic VMは現在サポートされていません。"},
        {"classpath:", "クラスパス: {0}"},
        {"colon mark", ":"},
        {"colon space", ": "},
        {"Command is not supported on the target VM", "コマンド''{0}''はターゲットVMではサポートされていません"},
        {"Command is not supported on a read-only VM connection", "コマンド''{0}''は読取り専用VM接続ではサポートされていません"},
        {"Command not valid until the VM is started with the run command", "コマンド''{0}''は、VMが''run''コマンドで開始されるまで無効です"},
        {"Condition must be boolean", "条件はbooleanである必要があります"},
        {"Connector and Transport name", "  コネクタ: {0}  トランスポート: {1}"},
        {"Connector argument nodefault", "    引数: {0} (デフォルトなし)"},
        {"Connector argument default", "    引数: {0} デフォルト値: {1}"},
        {"Connector description", "    説明: {0}"},
        {"Connector required argument nodefault", "    必須引数: {0} (デフォルトなし)"},
        {"Connector required argument default", "    必須引数: {0} デフォルト値: {1}"},
        {"Connectors available", "利用可能なコネクタ:"},
        {"Constant is not a method", "定数はメソッドではありません"},
        {"Could not open:", "開けませんでした: {0}"},
        {"Current method is native", "現在のメソッドはnativeです"},
        {"Current thread died. Execution continuing...", "現在のスレッド{0}が終了しました。実行が続行中..."},
        {"Current thread isnt suspended.", "現在のスレッドは中断されていません。"},
        {"Current thread not set.", "現在のスレッドが設定されていません。"},
        {"dbgtrace flag value must be an integer:", "dbgtraceフラグ値は整数である必要があります: {0}"},
        {"dbgtrace command value must be an integer:", "dbgtraceコマンド値は整数である必要があります: {0}"},
        {"Deferring.", "遅延した{0}。\nクラスがロードされた後に設定されます。"},
        {"End of stack.", "スタックの終わり。"},
        {"EOF", "EOF"},
        {"Error popping frame", "フレームのポップ中のエラー - {0}"},
        {"Error reading file", "''{0}''の読取りエラー - {1}"},
        {"Error redefining class to file", "{0}を{1}に再定義中のエラー - {2}"},
        {"exceptionSpec all", "すべての{0}"},
        {"exceptionSpec caught", "捕捉した{0}"},
        {"exceptionSpec uncaught", "捕捉されない{0}"},
        {"Exception in expression:", "式の例外: {0}"},
        {"Exception occurred caught", "例外が発生しました: {0} (捕捉される場所: {1})"},
        {"Exception occurred uncaught", "例外が発生しました: {0} (捕捉されない)"},
        {"Exceptions caught:", "次の例外が発生したときにブレーク:"},
        {"Expected at, in, or an integer <thread_id>:", "\"at\"、\"in\"または整数の<thread_id>が必要です: {0}"},
        {"expr is null", "{0} = null"},
        {"expr is value", "{0} = {1}"},
        {"expr is value <collected>", "  {0} = {1} <collected>"},
        {"Expression cannot be void", "式はvoid型にできません"},
        {"Expression must evaluate to an object", "式はオブジェクトとして評価される必要があります"},
        {"extends:", "拡張します: {0}"},
        {"Extra tokens after breakpoint location", "ブレークポイントの場所の後の追加トークン"},
        {"Failed reading output", "子のjavaインタープリタの出力の読取りに失敗しました。"},
        {"Fatal error", "致命的エラー:"},
        {"Field access encountered before after", "フィールド({0})は{1}で、{2}になります: "},
        {"Field access encountered", "フィールド({0})のアクセスが検出されました: "},
        {"Field to unwatch not specified", "ウォッチしないフィールドが指定されていません。"},
        {"Field to watch not specified", "ウォッチするフィールドが指定されていません。"},
        {"GC Disabled for", "{0}のGCが無効です:"},
        {"GC Enabled for", "{0}のGCが有効です:"},
        {"grouping begin character", "{"},
        {"grouping end character", "}"},
        {"Illegal Argument Exception", "不正な引数の例外です"},
        {"Illegal connector argument", "不正なコネクタ引数です: {0}"},
        {"Illegal thread state", "不正なスレッド状態です"},
        {"Illegal thread state (virtual thread not suspended)", "不正なスレッド状態です(仮想スレッドは中断していません)"},
        {"implementor:", "インプリメンタ: {0}"},
        {"implements:", "実装します: {0}"},
        {"Initializing progname", "{0}の初期化中..."},
        {"Input stream closed.", "入力ストリームが閉じられました。"},
        {"Interface:", "インタフェース: {0}"},
        {"Internal debugger error.", "デバッガの内部エラーです。"},
        {"Internal error: null ThreadInfo created", "内部エラー: nullのThreadInfoが作成されました"},
        {"Internal error; unable to set", "内部エラー。{0}を設定できません"},
        {"Internal exception during operation:", "操作中の内部例外:\n    {0}"},
        {"Internal exception:", "内部例外:"},
        {"Invalid argument type name", "引数型の名前が無効です"},
        {"Invalid assignment syntax", "割当て構文が無効です"},
        {"Invalid command syntax", "コマンド構文が無効です"},
        {"Invalid connect type", "接続型が無効です"},
        {"Invalid consecutive invocations", "連続呼出しが無効です"},
        {"Invalid exception object", "例外オブジェクトが無効です"},
        {"Invalid line number specified", "無効な行番号が指定されました"},
        {"Invalid <method_name> specification:", "無効な<method_name>指定: {0}"},
        {"Invalid option on class command", "classコマンドのオプションが無効です"},
        {"invalid option", "無効なオプション: {0}"},
        {"Invalid thread status.", "スレッド状態が無効です。"},
        {"Invalid <thread_id>:", "無効な<thread_id>: {0}"},
        {"Invalid transport name:", "トランスポート名が無効です: {0}"},
        {"Invalid <class>.<method_name> specification", "無効な<class>.<method_name>指定"},
        {"I/O exception occurred:", "入出力例外が発生しました: {0}"},
        {"is an ambiguous method name in", "\"{0}\"は\"{1}\"のあいまいなメソッド名です"},
        {"is an invalid line number for",  "{0,number,integer}は{1}の無効な行番号です"},
        {"is not a valid class name", "\"{0}\"は不正なクラス名です。"},
        {"is not a valid field name", "\"{0}\"は不正なフィールド名です。"},
        {"is not a valid id or class name", "\"{0}\"は不正なIDまたはクラス名です。"},
        {"is not a valid line number or method name for", "\"{0}\"はクラス\"{1}\"の不正な行番号またはメソッド名です"},
        {"is not a valid method name", "\"{0}\"は不正なメソッド名です。"},
        {"is not a valid thread id", "\"{0}\"は不正なスレッドIDです。"},
        {"is not a valid threadgroup name", "\"{0}\"は不正なスレッド・グループ名です。"},
        {"jdb prompt with no current thread", "> "},
        {"jdb prompt thread name and current stack frame", "{0}[{1,number,integer}] "},
        {"killed", "{0}が強制終了されました"},
        {"killing thread:", "強制終了するスレッド: {0}"},
        {"Line number information not available for", "ソース行番号はこの場所では使用できません。"},
        {"line number", ":{0,number,integer}"},
        {"list field typename and name", "{0} {1}\n"},
        {"list field typename and name inherited", "{0} {1} ({2}から継承)\n"},
        {"list field typename and name hidden", "{0} {1} (非表示)\n"},
        {"Listening at address:", "次のアドレスでリスニング: {0}"},
        {"Local variable information not available.", "ローカル変数情報がありません。変数情報を生成するには-gを指定してコンパイルしてください"},
        {"Local variables:", "ローカル変数:"},
        {"<location unavailable>", "<location unavailable>"},
        {"location", "\"スレッド={0}\", {1}"},
        {"locationString", "{0}.{1}()、行={2,number,integer} bci={3,number,integer}"},
        {"Main class and arguments must be specified", "メイン・クラスと引数を指定する必要があります"},
        {"Method arguments:", "メソッド引数:"},
        {"Method entered:", "入力されたメソッド: "},
        {"Method exited:",  "終了したメソッド"},
        {"Method exitedValue:", "メソッドが終了しました: 戻り値= {0}, "},
        {"Method is overloaded; specify arguments", "メソッド{0}がオーバーロードされています。引数を指定してください"},
        {"minus version", "これは{0}バージョン{1,number,integer}.{2,number,integer} (Java SEバージョン{3})です"},
        {"Missing at or in", "\"at\"または\"in\"がありません"},
        {"Monitor information for thread", "スレッド{0}の情報のモニター:"},
        {"Monitor information for expr", "{0} ({1})の情報のモニター:"},
        {"More than one class named", "名前''{0}''のクラスが複数あります"},
        {"native method", "nativeメソッド"},
        {"nested:", "ネストされています: {0}"},
        {"No attach address specified.", "接続アドレスが指定されていません。"},
        {"No breakpoints set.", "ブレークポイントが設定されていません。"},
        {"No class named", "名前''{0}''のクラスがありません"},
        {"No class specified.", "クラスが指定されていません。"},
        {"No classpath specified.", "クラスパスが指定されていません。"},
        {"No code at line", "{1}の行{0,number,integer}にコードがありません"},
        {"No connect specification.", "接続が指定されていません。"},
        {"No connector named:", "名前{0}のコネクタがありません"},
        {"No current thread", "現在のスレッドがありません"},
        {"No default thread specified:", "デフォルトのスレッドが指定されていません。最初に\"thread\"コマンドを使用してください。"},
        {"No exception object specified.", "例外オブジェクトが指定されていません。"},
        {"No exceptions caught.", "例外が捕捉されませんでした。"},
        {"No expression specified.", "式が指定されていません。"},
        {"No field in", "{1}にフィールド{0}がありません"},
        {"No frames on the current call stack", "現在のコール・スタックにフレームがありません"},
        {"No linenumber information for", "{0}の行番号情報がありません。デバッグをオンにしてコンパイルしてください。"},
        {"No local variables", "ローカル変数がありません"},
        {"No method in", "{1}にメソッド{0}がありません"},
        {"No method specified.", "メソッドが指定されていません。"},
        {"No monitor numbered:", "番号付けされているモニターがありません: {0}"},
        {"No monitors owned", "  所有されているモニターがありません"},
        {"No object specified.", "オブジェクトが指定されていません。"},
        {"No objects specified.", "オブジェクトが指定されていません。"},
        {"No save index specified.", "保存インデックスが指定されていません。"},
        {"No saved values", "保存された値がありません"},
        {"No source information available for:", "{0}のソース情報が利用できません"},
        {"No sourcedebugextension specified", "SourceDebugExtensionが指定されていません"},
        {"No sourcepath specified.", "ソース・パスが指定されていません。"},
        {"No thread specified.", "スレッドが指定されていません。"},
        {"No VM connected", "VMが接続されていません"},
        {"No waiters", "  待機はありません"},
        {"not a class", "{0}はクラスではありません"},
        {"Not a monitor number:", "モニター番号ではありません: ''{0}''"},
        {"not found (try the full name)", "{0}が見つかりません(フルネームを試してください)"},
        {"Not found:", "見つかりません: {0}"},
        {"not found", "{0}が見つかりません"},
        {"Not owned", "  所有されていません"},
        {"Not waiting for a monitor", "  モニターを待機していません"},
        {"Nothing suspended.", "何も中断されていません。"},
        {"object description and id", "({0}){1}"},
        {"Operation is not supported on the current frame", "操作は現在のフレームでサポートされていません"},
        {"operation not yet supported", "まだサポートされていない操作"},
        {"Owned by:", "  所有者: {0}、エントリ数: {1,number,integer}"},
        {"Owned monitor:", "  所有されているモニター: {0}"},
        {"Parse exception:", "例外の解析: {0}"},
        {"printclearcommandusage", "使用方法 clear <class>:<line_number>または\n      clear <class>.<method_name>[(argument_type,...)]"},
        {"printstopcommandusage",
         "使用方法: stop [go|thread] [<thread_id>] <at|in> <location>\n  \"go\"が指定されている場合は、停止後すぐに再開します\n  \"thread\"が指定されている場合は、停止したスレッドのみ中断します\n  \"go\"も\"thread\"も指定されていない場合は、すべてのスレッドを中断します\n  整数の<thread_id>が指定されている場合は、指定されたスレッドでのみ停止します\n  \"at\"と\"in\"は同じ意味を持ちます\n  <location>は行番号またはメソッドにすることができます:\n    <class_id>:<line_number>\n    <class_id>.<method>[(argument_type,...)]"
        },
        {"Removed:", "{0}は削除されました"},
        {"repeat is on", "繰返しはオンです"},
        {"repeat is off", "繰返しはオフです"},
        {"repeat usage", "使用方法: repeat <on|off>"},
        {"Requested stack frame is no longer active:", "リクエストされたスタック・フレームは現在アクティブではありません: {0,number,integer}"},
        {"run <args> command is valid only with launched VMs", "'run <args>'コマンドは起動済のVMでのみ有効です"},
        {"run", "{0}の実行"},
        {"saved", "{0}が保存されました"},
        {"Set deferred", "遅延した{0}の設定"},
        {"Set", "{0}の設定"},
        {"Source file not found:", "ソース・ファイルが見つかりません: {0}"},
        {"source line number and line", "{0,number,integer}    {1}"},
        {"source line number current line and line", "{0,number,integer} => {1}"},
        {"sourcedebugextension", "SourceDebugExtension -- {0}"},
        {"Specify class and method", "クラスとメソッドの指定"},
        {"Specify classes to redefine", "再定義するクラスの指定"},
        {"Specify file name for class", "クラス{0}のファイル名の指定"},
        {"stack frame dump with pc", "  [{0,number,integer}] {1}.{2} ({3})、pc = {4}"},
        {"stack frame dump", "  [{0,number,integer}] {1}.{2} ({3})"},
        {"Step completed:", "ステップが完了しました: "},
        {"Stopping due to deferred breakpoint errors.", "遅延したブレークポイント・エラーが原因で停止しています。\n"},
        {"subclass:", "サブクラス: {0}"},
        {"subinterface:", "サブインタフェース: {0}"},
        {"tab", "\t{0}"},
        {"Target VM failed to initialize.", "ターゲットVMが初期化に失敗しました。"},
        {"The application exited", "アプリケーションが終了しました"},
        {"The application has been disconnected", "アプリケーションが切断されました"},
        {"The gc command is no longer necessary.", "'gc'コマンドは不要になりました。\nすべてのオブジェクトは通常どおりガベージ・コレクションされます。個々のオブジェクトの\nガベージ・コレクションを制御するには'enablegc'および'disablegc'コマンドを使用してください。"},
        {"The load command is no longer supported.", "'load'コマンドは現在サポートされていません。"},
        {"The memory command is no longer supported.", "'memory'コマンドは現在サポートされていません。"},
        {"The VM does not use paths", "VMはパスを使用しません"},
        {"Thread is not running (no stack).", "スレッドは実行中ではありません(スタックなし)。"},
        {"Thread number not specified.", "スレッド番号が指定されていません。"},
        {"Thread:", "{0}:"},
        {"Thread Group:", "グループ{0}:"},
        {"Thread description name unknownStatus BP",  "  {0} {1}は不明です(ブレークポイント)"},
        {"Thread description name unknownStatus",     "  {0} {1}は不明です"},
        {"Thread description name zombieStatus BP",   "  {0} {1}はゾンビです(ブレークポイント地点)"},
        {"Thread description name zombieStatus",      "  {0} {1}はゾンビです"},
        {"Thread description name runningStatus BP",  "  {0} {1}は実行中です(ブレークポイント)"},
        {"Thread description name runningStatus",     "  {0} {1}は実行中です"},
        {"Thread description name sleepingStatus BP", "  {0} {1}はスリープ中です(ブレークポイント)"},
        {"Thread description name sleepingStatus",    "  {0} {1}はスリープ中です"},
        {"Thread description name waitingStatus BP",  "  {0} {1}はモニター内で待機中です(ブレークポイント)"},
        {"Thread description name waitingStatus",     "  {0} {1}はモニター内で待機中です"},
        {"Thread description name condWaitstatus BP", "  {0} {1}は条件を待機中です(ブレークポイント)"},
        {"Thread description name condWaitstatus",    "  {0} {1}は条件を待機中です"},
        {"Thread has been resumed", "スレッドが再開しました"},
        {"Thread not suspended", "スレッドは中断していません"},
        {"thread group number description name", "{0,number,integer}. {1} {2}"},
        {"<thread_id> option not valid until the VM is started with the run command",
         "<thread_id>オプションは、VMがrunコマンドで開始されるまで無効です"},
        {"Threads must be suspended", "スレッドを中断する必要があります"},
        {"trace method exit in effect for", "{0}に対して有効なメソッド終了のトレース"},
        {"trace method exits in effect", "有効なメソッド終了のトレース"},
        {"trace methods in effect", "メソッドのトレースの有効化"},
        {"trace go method exit in effect for", "{0}に有効なgoメソッド終了のトレース"},
        {"trace go method exits in effect", "有効なgoメソッド終了のトレース"},
        {"trace go methods in effect", "goメソッドのトレースの有効化"},
        {"trace not in effect", "トレースの無効化"},
        {"Unable to attach to target VM.", "ターゲットVMに接続できません。"},
        {"Unable to display process output:", "プロセス出力を表示できません: {0}"},
        {"Unable to launch target VM.", "ターゲットVMを起動できません。"},
        {"Unable to set deferred", "遅延した{0}を設定できません: {1}"},
        {"Unable to set main class and arguments", "メイン・クラスと引数を指定できません"},
        {"Unable to set", "{0}を設定できません: {1}"},
        {"Unexpected event type", "予期しないイベント・タイプ: {0}"},
        {"unknown", "不明"},
        {"Unmonitoring", "{0}のモニタリング解除 "},
        {"Unrecognized command.  Try help...", "''{0}''は認識されないコマンドです。helpで確認してください..."},
        {"Usage: catch exception", "使用方法: catch [uncaught|caught|all] <class id>|<class pattern>"},
        {"Usage: ignore exception", "使用方法: ignore [uncaught|caught|all] <class id>|<class pattern>"},
        {"Usage: down [n frames]", "使用方法: down [n frames]"},
        {"Usage: kill <thread id> <throwable>", "使用方法: kill <thread id> <throwable>"},
        {"Usage: read <command-filename>", "使用方法: read <command-filename>"},
        {"Usage: unmonitor <monitor#>", "使用方法: unmonitor <monitor#>"},
        {"Usage: up [n frames]", "使用方法: up [n frames]"},
        {"Use java minus X to see", "使用可能な非標準オプションを表示するには'java -X'を使用してください"},
        {"VM already running. use cont to continue after events.", "VMはすでに実行中です。イベント後に続行するには'cont'を使用してください。"},
        {"VM Started:", "VMが開始されました: "},
        {"vmstartexception", "VMが例外を開始しました: {0}"},
        {"Waiting for monitor:", "   モニターの待機中: {0}"},
        {"Waiting thread:", " スレッドを待機中: {0}"},
        {"watch accesses of", "{0}.{1}のアクセスをウォッチ"},
        {"watch modification of", "{0}.{1}の変更のウォッチ"},
        {"zz help text",
             "** コマンド・リスト **\nconnectors                -- このVM内の使用可能なコネクタとトランスポートをリストします\n\nrun [class [args]]        -- アプリケーションのメイン・クラスの実行を開始します\n\nthreads [threadgroup]     -- スレッドグループ内のスレッドをリストします。指定がない場合は、現在のスレッドグループを使用します。\nthread <thread id>        -- デフォルトのスレッドを設定します\nsuspend [thread id(s)]    -- スレッドを中断します(デフォルト: すべて)\nresume [thread id(s)]     -- スレッドを再開します(デフォルト: すべて)\nwhere [<thread id> | all] -- スレッドのスタックをダンプします\nwherei [<thread id> | all]-- スレッドのスタックをpc情報とともにダンプします\nup [n frames]             -- スレッドのスタックを上に移動します\ndown [n frames]           -- スレッドのスタックを下に移動します\nkill <thread id> <expr>   -- 指定された例外オブジェクトでスレッドを強制終了します\ninterrupt <thread id>     -- スレッドを中断します\n\nprint <expr>              -- 式の値を出力します\ndump <expr>               -- すべてのオブジェクト情報を出力します\neval <expr>               -- 式を評価します(printと同じ)\nset <lvalue> = <expr>     -- 新しい値をフィールド/変数/配列要素に代入します\nlocals                    -- 現在のスタック・フレーム内のすべてのローカル変数を出力します\n\nclasses                   -- 現在既知のクラスをリストします\nclass <class id>          -- 指定したクラスの詳細を表示します\nmethods <class id>        -- クラスのメソッドをリストします\nfields <class id>         -- クラスのフィールドをリストします\n\nthreadgroups              -- スレッドグループをリストします\nthreadgroup <name>        -- 現在のスレッドグループを<name>に設定します\nthreadgroup               -- 現在のスレッドグループを最上位レベルのスレッドグループに設定します\n\nstop [go|thread] [<thread_id>] <at|in> <location>\n                          -- ブレークポイントを設定します\n                          -- オプションが指定されていない場合は、ブレークポイントの現在のリストが出力されます\n                          -- \"go\"が指定されている場合は、停止後すぐに再開します\n                          -- \"thread\"が指定されている場合は、停止したスレッドのみ中断します\n                          -- \"go\"も\"thread\"も指定されていない場合は、すべてのスレッドを中断します\n                          -- 整数の<thread_id>が指定されている場合は、指定されたスレッドでのみ停止します\n                          -- \"at\"と\"in\"は同じ意味を持ちます\n                          -- <location>は行番号またはメソッドにすることができます:\n                          --   <class_id>:<line_number>\n                          --   <class_id>.<method>[(argument_type,...)]\nclear <class id>.<method>[(argument_type,...)]\n                          -- メソッド内のブレークポイントをクリアします\nclear <class id>:<line>   -- 行のブレークポイントをクリアします\nclear                     -- ブレークポイントをリストします\ncatch [uncaught|caught|all] <class id>|<class pattern>\n                          -- 指定された例外が発生したときにブレークします\nignore [uncaught|caught|all] <class id>|<class pattern>\n                          -- 指定された例外の'catch'を取り消します\nwatch [access|all] <class id>.<field name>\n                          -- フィールドへのアクセスまたは変更をウォッチします\nunwatch [access|all] <class id>.<field name>\n                          -- フィールドへのアクセスまたは変更のウォッチを中止します\ntrace [go] methods [thread]\n                          -- メソッドの入り口と出口をトレースします。\n                          -- 'go'が指定されるまですべてのスレッドは中断します\ntrace [go] method exit | exits [thread]\n                          -- 現在のメソッドの出口またはすべてのメソッドの出口をトレースします\n                          -- 'go'が指定されるまですべてのスレッドは中断します\nuntrace [methods]         -- メソッドの開始または終了のトレースを停止します\nstep                      -- 現在の行を実行します\nstep up                   -- 現在のメソッドがメソッドの呼出し元に戻るまで実行します\nstepi                     -- 現在の命令を実行します\nnext                      -- 1行をステップ実行します(呼出しをステップオーバー)\ncont                      -- ブレークポイントから実行を続行します\n\nlist [line number|method] -- ソース・コードを出力します\nuse (or sourcepath) [source file path]\n                          -- ソース・パスを表示または変更します\nexclude [<class pattern>, ... | \"none\"]\n                          -- 指定したクラスのステップやメソッド・イベントを報告しません\nclasspath                 -- ターゲットVMからクラスパス情報を出力します\n\nmonitor <command>         -- プログラムが停止するたびにコマンドを実行します\nmonitor                   -- モニターをリストします\nunmonitor <monitor#>      -- モニターを削除します\nread <filename>           -- コマンド・ファイルを読み取って実行します\n\nlock <expr>               -- オブジェクトのロック情報を出力します\nthreadlocks [thread id]   -- スレッドのロック情報を出力します\n\npop                       -- 現在のフレームまでのすべてのスタックをポップします\nreenter                   -- popと同じですが、現在のフレームが再入力されます\nredefine <class id> <class file name>\n                          -- クラスのコードを再定義します\n\ndisablegc <expr>          -- オブジェクトのガベージ・コレクションを抑制します\nenablegc <expr>           -- オブジェクトのガベージ・コレクションを許可します\n\n!!                        -- 最後のコマンドを繰り返します\n<n> <command>             -- コマンドをn回繰り返します\nrepeat                    -- GDB形式の空のコマンドの繰返しが有効になっているかどうかを示します\nrepeat <on|off>           -- GDB形式の繰返しを有効/無効にします\n# <command>               -- 破棄します(操作なし)\nhelp (または?)               -- コマンドをリストします\ndbgtrace [flag]           -- dbgtraceコマンド・ライン・オプションと同じです\nversion                   -- バージョン情報を出力します\nexit (またはquit)            -- デバッガを終了します\n\n<class id>: パッケージ修飾子を含む完全クラス名\n<class pattern>: 先頭または末尾のワイルドカード('*')を含むクラス名\n<thread id>: 'threads'コマンドで報告されるスレッド番号\n<expr>: Java(TM)プログラミング言語の式。\nほとんどの一般的な構文がサポートされています。\n\n起動コマンドは、\"jdb.ini\"または\".jdbrc\"に配置できます\n(user.homeまたはuser.dir内)"},
        {"zz usage text",
             "使用方法: {0} <options> <class> <arguments>\n\nオプションは次のとおりです:\n    -? -h --help -help このヘルプ・メッセージを出力して終了する\n    -sourcepath <directories separated by \"{1}\">\n                      ソース・ファイルを検索するディレクトリ\n    -attach <address>\n                      標準コネクタを使用して、指定されたアドレスで実行中のVMに接続する\n    -listen <address>\n                      標準コネクタを使用して、指定されたアドレスで実行中のVMの接続を待機する\n    -listenany\n                      標準コネクタを使用して、使用可能な任意のアドレスで実行中のVMの接続を待機する\n    -launch\n                      ''run''コマンドを待機せずにVMを即時に起動する\n    -listconnectors   このVMで使用可能なコネクタをリストする\n    -connect <connector-name>:<name1>=<value1>,...\n                      指定されたコネクタを使用して、リストされた引数値でターゲットVMに接続する\n    -dbgtrace [flags] {0}のデバッグの情報を出力する\n    -trackallthreads  仮想スレッドを含むすべてのスレッドをトラッキングする。\n    -tclient          アプリケーションをHotSpot(TM) Client Compilerで実行する\n    -tserver          アプリケーションをHotSpot(TM) Server Compilerで実行する\n    -R<option>        jdbによって起動された場合に、デバッグするプロセスに<option>を転送する。それ以外の場合は無視される\n\njdbによって起動された場合に、デバッグするプロセスに転送されるオプション(-Rを使用しない省略表記):\n    -v -verbose[:class|gc|jni]\n                      詳細モードをオンにする\n    -D<name>=<value>  システム・プロパティを設定する\n    -classpath <directories separated by \"{1}\">\n                      クラスを検索するディレクトリをリストする\n    -X<option>        非標準のターゲットVMオプション\n\n<class>はデバッグを開始するクラスの名前です\n<arguments>は<class>のmain()メソッドに渡される引数です\n\nコマンドのヘルプについては{0}プロンプトで''help''を入力してください"},
        // END OF MATERIAL TO LOCALIZE
        };

        return temp;
    }
}
