/*
 * Copyright (c) 1996, 2010, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */
package sun.applet.resources;

import java.util.ListResourceBundle;

public class MsgAppletViewer_pt_BR extends ListResourceBundle {

    public Object[][] getContents() {
        return new Object[][] {
            {"textframe.button.dismiss", "Rejeitar"},
            {"appletviewer.tool.title", "Visualizador de applet: {0}"},
            {"appletviewer.menu.applet", "Applet"},
            {"appletviewer.menuitem.restart", "Reiniciar"},
            {"appletviewer.menuitem.reload", "Recarregar"},
            {"appletviewer.menuitem.stop", "Parar"},
            {"appletviewer.menuitem.save", "Salvar..."},
            {"appletviewer.menuitem.start", "Iniciar"},
            {"appletviewer.menuitem.clone", "Clonar..."},
            {"appletviewer.menuitem.tag", "Marca..."},
            {"appletviewer.menuitem.info", "Info..."},
            {"appletviewer.menuitem.edit", "Editar"},
            {"appletviewer.menuitem.encoding", "Codifica\u00e7\u00e3o de caracteres"},
            {"appletviewer.menuitem.print", "Imprimir..."},
            {"appletviewer.menuitem.props", "Propriedades..."},
            {"appletviewer.menuitem.close", "Fechar"},
            {"appletviewer.menuitem.quit", "Sair"},
            {"appletviewer.label.hello", "Ol\u00e1..."},
            {"appletviewer.status.start", "iniciando applet..."},
            {"appletviewer.appletsave.filedialogtitle","Serializar applet no arquivo"},
            {"appletviewer.appletsave.err1", "serializando um {0} para {1}"},
            {"appletviewer.appletsave.err2", "em appletSave: {0}"},
            {"appletviewer.applettag", "Marca exibida"},
            {"appletviewer.applettag.textframe", "Marca HTML do applet"},
            {"appletviewer.appletinfo.applet", "-- sem informa\u00e7\u00f5es do applet --"},
            {"appletviewer.appletinfo.param", "-- sem informa\u00e7\u00f5es do par\u00e2metro --"},
            {"appletviewer.appletinfo.textframe", "Informa\u00e7\u00f5es do applet"},
            {"appletviewer.appletprint.fail", "Falha na impress\u00e3o."},
            {"appletviewer.appletprint.finish", "Impress\u00e3o finalizada."},
            {"appletviewer.appletprint.cancel", "Impress\u00e3o cancelada."},
            {"appletviewer.appletencoding", "Codifica\u00e7\u00e3o de caracteres: {0}"},
            {"appletviewer.parse.warning.requiresname", "Aviso: a marca <param name=... value=...> requer nome do atributo."},
            {"appletviewer.parse.warning.paramoutside", "Aviso: marca <param> fora de <applet> ... </applet>."},
            {"appletviewer.parse.warning.applet.requirescode", "Aviso: marca <applet> requer c\u00f3digo de atributo."},
            {"appletviewer.parse.warning.applet.requiresheight", "Aviso: marca <applet> requer atributo de altura."},
            {"appletviewer.parse.warning.applet.requireswidth", "Aviso: marca <applet> requer atributo de largura."},
            {"appletviewer.parse.warning.object.requirescode", "Aviso: marca <object> requer c\u00f3digo de atributo."},
            {"appletviewer.parse.warning.object.requiresheight", "Aviso: marca <object> requer atributo de altura."},
            {"appletviewer.parse.warning.object.requireswidth", "Aviso: marca <object> requer atributo de largura."},
            {"appletviewer.parse.warning.embed.requirescode", "Aviso: marca <embed> requer c\u00f3digo de atributo."},
            {"appletviewer.parse.warning.embed.requiresheight", "Aviso: marca <embed> requer atributo de altura."},
            {"appletviewer.parse.warning.embed.requireswidth", "Aviso: marca <embed> requer atributo de largura."},
            {"appletviewer.parse.warning.appnotLongersupported", "Aviso: marca <app> n\u00e3o mais suportada, usar <applet> em seu lugar:"},
            {"appletviewer.usage", "Uso: url(s) de <options> do visualizador de applets\n\nem que <options> inclui:\n  -debug                  inicia o visualizador de applet no depurador Java\n  -encoding <encoding>    especifica a codifica\u00e7\u00e3o de caracteres usada pelos arquivos HTML\n  -J<runtime flag>        passa o argumento para o int\u00e9rprete de java\n\nA op\u00e7\u00e3o -J n\u00e3o \u00e9 padr\u00e3o e est\u00e1 sujeita a altera\u00e7\u00f5es sem aviso."},
            {"appletviewer.main.err.unsupportedopt", "Op\u00e7\u00e3o n\u00e3o suportada: {0}"},
            {"appletviewer.main.err.unrecognizedarg", "Argumento n\u00e3o reconhecido: {0}"},
            {"appletviewer.main.err.dupoption", "Uso duplicado da op\u00e7\u00e3o: {0}"},
        {"appletviewer.main.err.inputfile", "Nenhum arquivo de entrada especificado."},
            {"appletviewer.main.err.badurl", "URL incorreto: {0} ( {1} )"},
            {"appletviewer.main.err.io", "Exce\u00e7\u00e3o de E/S durante a leitura: {0}"},
            {"appletviewer.main.err.readablefile", "Certifique-se de que {0} seja um arquivo e seja leg\u00edvel."},
            {"appletviewer.main.err.correcturl", "{0} \u00e9 o URL correto?"},
            {"appletviewer.main.prop.store", "Propriedades espec\u00edficas do usu\u00e1rio para AppletViewer"},
        {"appletviewer.main.err.prop.cantread", "N\u00e3o \u00e9 poss\u00edvel ler o arquivo de propriedades do usu\u00e1rio: {0}"},
            {"appletviewer.main.err.prop.cantsave", "N\u00e3o \u00e9 poss\u00edvel salvar o arquivo de propriedades do usu\u00e1rio: {0}"},
            {"appletviewer.main.warn.nosecmgr", "Aviso: desabilitando a seguran\u00e7a."},
        {"appletviewer.main.debug.cantfinddebug", "N\u00e3o \u00e9 poss\u00edvel localizar o depurador!"},
        {"appletviewer.main.debug.cantfindmain", "N\u00e3o \u00e9 poss\u00edvel localizar o m\u00e9todo principal no depurador!"},
            {"appletviewer.main.debug.exceptionindebug", "Exce\u00e7\u00e3o no depurador!"},
        {"appletviewer.main.debug.cantaccess", "N\u00e3o \u00e9 poss\u00edvel acessar o depurador!"},
            {"appletviewer.main.nosecmgr", "Aviso: SecurityManager n\u00e3o instalado!"},
            {"appletviewer.main.warning", "Aviso: nenhum applet foi iniciado. Certifique-se de que a entrada contenha uma marca <applet>."},
            {"appletviewer.main.warn.prop.overwrite", "Aviso: substituindo temporariamente a propriedade do sistema em solicita\u00e7\u00e3o do usu\u00e1rio: chave: {0} valor antigo: {1} valor novo: {2}"},
            {"appletviewer.main.warn.cantreadprops", "Aviso: n\u00e3o \u00e9 poss\u00edvel ler o arquivo de propriedades do AppletViewer: {0} usando padr\u00f5es."},
        {"appletioexception.loadclass.throw.interrupted", "carregamento de classe interrompido: {0}"},
            {"appletioexception.loadclass.throw.notloaded", "classe n\u00e3o carregada: {0}"},
            {"appletclassloader.loadcode.verbose", "Abrindo fluxo para: {0} para obter {1}"},
            {"appletclassloader.filenotfound", "Arquivo n\u00e3o encontrado ao procurar por: {0}"},
            {"appletclassloader.fileformat", "Exce\u00e7\u00e3o de formato de arquivo ao carregar: {0}"},
            {"appletclassloader.fileioexception", "Exce\u00e7\u00e3o de E/S ao carregar: {0}"},
            {"appletclassloader.fileexception", "Exce\u00e7\u00e3o {0} ao carregar: {0}"},
            {"appletclassloader.filedeath", "{0} eliminado ao carregar: {1}"},
            {"appletclassloader.fileerror", "Erro {0} ao carregar: {1}"},
            {"appletclassloader.findclass.verbose.findclass", "{0} encontra classe {1}"},
            {"appletclassloader.findclass.verbose.openstream", "Abrindo fluxo para: {0} para obter {1}"},
            {"appletclassloader.getresource.verbose.forname", "AppletClassLoader.getResource do nome: {0}"},
            {"appletclassloader.getresource.verbose.found", "Recurso encontrado: {0} como um recurso do sistema"},
            {"appletclassloader.getresourceasstream.verbose", "Recurso encontrado: {0} como um recurso do sistema"},
            {"appletpanel.runloader.err", "Par\u00e2metro de c\u00f3digo ou objeto!"},
            {"appletpanel.runloader.exception", "exce\u00e7\u00e3o ao desserializar {0}"},
            {"appletpanel.destroyed", "Applet destru\u00eddo."},
            {"appletpanel.loaded", "Applet carregado."},
            {"appletpanel.started", "Applet iniciado."},
            {"appletpanel.inited", "Applet inicializado."},
            {"appletpanel.stopped", "Applet interrompido."},
            {"appletpanel.disposed", "Applet descartado."},
            {"appletpanel.nocode", "Marca APPLET ausente no par\u00e2metro CODE."},
            {"appletpanel.notfound", "carregar: classe {0} n\u00e3o encontrada."},
            {"appletpanel.nocreate", "carregar: {0} n\u00e3o pode ser instanciado."},
            {"appletpanel.noconstruct", "carregar: {0} n\u00e3o \u00e9 p\u00fablico ou n\u00e3o possui um construtor p\u00fablico."},
            {"appletpanel.death", "eliminado"},
            {"appletpanel.exception", "exce\u00e7\u00e3o: {0}."},
            {"appletpanel.exception2", "exce\u00e7\u00e3o: {0}: {1}."},
            {"appletpanel.error", "erro: {0}."},
            {"appletpanel.error2", "erro: {0}: {1}."},
            {"appletpanel.notloaded", "Inicializar: applet n\u00e3o carregado."},
            {"appletpanel.notinited", "Iniciar: applet n\u00e3o inicializado."},
            {"appletpanel.notstarted", "Parar: applet n\u00e3o iniciado."},
            {"appletpanel.notstopped", "Destruir: applet n\u00e3o interrompido."},
            {"appletpanel.notdestroyed", "Descartar: applet n\u00e3o destru\u00eddo."},
            {"appletpanel.notdisposed", "Carregar: applet n\u00e3o descartado."},
            {"appletpanel.bail", "Interrompido: salvando."},
            {"appletpanel.filenotfound", "Arquivo n\u00e3o encontrado ao procurar por: {0}"},
            {"appletpanel.fileformat", "Exce\u00e7\u00e3o de formato de arquivo ao carregar: {0}"},
            {"appletpanel.fileioexception", "Exce\u00e7\u00e3o de E/S ao carregar: {0}"},
            {"appletpanel.fileexception", "Exce\u00e7\u00e3o {0} ao carregar: {0}"},
            {"appletpanel.filedeath", "{0} eliminado ao carregar: {1}"},
            {"appletpanel.fileerror", "Erro {0} ao carregar: {1}"},
            {"appletpanel.badattribute.exception", "An\u00e1lise de HTML: valor incorreto do atributo de largura/altura"},
            {"appletillegalargumentexception.objectinputstream", "AppletObjectInputStream requer carregador n\u00e3o nulo"},
            {"appletprops.title", "Propriedades do AppletViewer"},
            {"appletprops.label.http.server", "Servidor proxy de http:"},
            {"appletprops.label.http.proxy", "Porta do proxy de http:"},
            {"appletprops.label.network", "Acesso \u00e0 rede:"},
            {"appletprops.choice.network.item.none", "Nenhum"},
            {"appletprops.choice.network.item.applethost", "Host do applet"},
            {"appletprops.choice.network.item.unrestricted", "N\u00e3o registrado"},
            {"appletprops.label.class", "Acesso \u00e0 classe:"},
            {"appletprops.choice.class.item.restricted", "Restrito"},
            {"appletprops.choice.class.item.unrestricted", "N\u00e3o registrado"},
            {"appletprops.label.unsignedapplet", "Permitir applets n\u00e3o assinados:"},
            {"appletprops.choice.unsignedapplet.no", "N\u00e3o"},
            {"appletprops.choice.unsignedapplet.yes", "Sim"},
            {"appletprops.button.apply", "Aplicar"},
            {"appletprops.button.cancel", "Cancelar"},
            {"appletprops.button.reset", "Redefinir"},
            {"appletprops.apply.exception", "Falha ao salvar propriedades: {0}"},
            /* 4066432 */
        {"appletprops.title.invalidproxy", "Entrada inv\u00e1lida"},
        {"appletprops.label.invalidproxy", "A porta do proxy deve ser um valor inteiro positivo."},
        {"appletprops.button.ok", "OK"},
        /* end 4066432 */
            {"appletprops.prop.store", "Propriedades espec\u00edficas do usu\u00e1rio para AppletViewer"},
            {"appletsecurityexception.checkcreateclassloader", "Exce\u00e7\u00e3o de seguran\u00e7a: classloader"},
            {"appletsecurityexception.checkaccess.thread", "Exce\u00e7\u00e3o de seguran\u00e7a: thread"},
            {"appletsecurityexception.checkaccess.threadgroup", "Exce\u00e7\u00e3o de seguran\u00e7a: threadgroup: {0}"},
            {"appletsecurityexception.checkexit", "Exce\u00e7\u00e3o de seguran\u00e7a: exit: {0}"},
            {"appletsecurityexception.checkexec", "Exce\u00e7\u00e3o de seguran\u00e7a: exec: {0}"},
            {"appletsecurityexception.checklink", "Exce\u00e7\u00e3o de seguran\u00e7a: link: {0}"},
            {"appletsecurityexception.checkpropsaccess", "Exce\u00e7\u00e3o de seguran\u00e7a: properties"},
            {"appletsecurityexception.checkpropsaccess.key", "Exce\u00e7\u00e3o de seguran\u00e7a: properties access {0}"},
            {"appletsecurityexception.checkread.exception1", "Exce\u00e7\u00e3o de seguran\u00e7a: {0}, {1}"},
            {"appletsecurityexception.checkread.exception2", "Exce\u00e7\u00e3o de seguran\u00e7a: file.read: {0}"},
            {"appletsecurityexception.checkread", "Exce\u00e7\u00e3o de seguran\u00e7a: file.read: {0} == {1}"},
            {"appletsecurityexception.checkwrite.exception", "Exce\u00e7\u00e3o de seguran\u00e7a: {0}, {1}"},
            {"appletsecurityexception.checkwrite", "Exce\u00e7\u00e3o de seguran\u00e7a: file.write: {0} == {1}"},
            {"appletsecurityexception.checkread.fd", "Exce\u00e7\u00e3o de seguran\u00e7a: fd.read"},
            {"appletsecurityexception.checkwrite.fd", "Exce\u00e7\u00e3o de seguran\u00e7a: fd.write"},
            {"appletsecurityexception.checklisten", "Exce\u00e7\u00e3o de seguran\u00e7a: socket.listen: {0}"},
            {"appletsecurityexception.checkaccept", "Exce\u00e7\u00e3o de seguran\u00e7a: socket.accept: {0} == {1}"},
            {"appletsecurityexception.checkconnect.networknone", "Exce\u00e7\u00e3o de seguran\u00e7a: socket.connect: {0} == {1}"},
            {"appletsecurityexception.checkconnect.networkhost1", "Exce\u00e7\u00e3o de seguran\u00e7a: n\u00e3o foi poss\u00edvel conectar a {0} com a origem de {1}."},
            {"appletsecurityexception.checkconnect.networkhost2", "Exce\u00e7\u00e3o de seguran\u00e7a: n\u00e3o foi poss\u00edvel resolver o IP para o host {0} ou para {1}. "},
            {"appletsecurityexception.checkconnect.networkhost3", "Exce\u00e7\u00e3o de seguran\u00e7a: n\u00e3o foi poss\u00edvel resolver o IP para o host {0}. Consulte a propriedade trustProxy."},
            {"appletsecurityexception.checkconnect", "Exce\u00e7\u00e3o de seguran\u00e7a: connect: {0}->{1}"},
            {"appletsecurityexception.checkpackageaccess", "Exce\u00e7\u00e3o de seguran\u00e7a: n\u00e3o \u00e9 poss\u00edvel acessar o pacote: {0}"},
            {"appletsecurityexception.checkpackagedefinition", "Exce\u00e7\u00e3o de seguran\u00e7a: n\u00e3o \u00e9 poss\u00edvel definir o pacote: {0}"},
            {"appletsecurityexception.cannotsetfactory", "Exce\u00e7\u00e3o de seguran\u00e7a: n\u00e3o \u00e9 poss\u00edvel definir a f\u00e1brica"},
            {"appletsecurityexception.checkmemberaccess", "Exce\u00e7\u00e3o de seguran\u00e7a: verificar acesso de membro"},
            {"appletsecurityexception.checkgetprintjob", "Exce\u00e7\u00e3o de seguran\u00e7a: getPrintJob"},
            {"appletsecurityexception.checksystemclipboardaccess", "Exce\u00e7\u00e3o de seguran\u00e7a: getSystemClipboard"},
            {"appletsecurityexception.checkawteventqueueaccess", "Exce\u00e7\u00e3o de seguran\u00e7a: getEventQueue"},
            {"appletsecurityexception.checksecurityaccess", "Exce\u00e7\u00e3o de seguran\u00e7a: opera\u00e7\u00e3o de seguran\u00e7a: {0}"},
            {"appletsecurityexception.getsecuritycontext.unknown", "tipo desconhecido de carregador de classe. n\u00e3o \u00e9 poss\u00edvel verificar para getContext"},
            {"appletsecurityexception.checkread.unknown", "tipo desconhecido de carregador de classe. n\u00e3o \u00e9 poss\u00edvel verificar para verifica\u00e7\u00e3o de leitura  {0}"},
            {"appletsecurityexception.checkconnect.unknown", "tipo desconhecido de carregador de classe. n\u00e3o \u00e9 poss\u00edvel verificar para verifica\u00e7\u00e3o de conex\u00e3o"},
        };
    }
}
