#
# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.  Oracle designates this
# particular file as subject to the "Classpath" exception as provided
# by Oracle in the LICENSE file that accompanied this code.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
#

name: 'OpenJDK GHA Rebuild Caches'

# Dry run rebuilds the caches in current branch, so they can be reused
# for any child PR branches. Because of this, we want to trigger this
# workflow in master branch, so that actual PR branches can use this cache.
# This workflow would trigger every time contributors sync their forked masters.
# We can limit the re-runs to the cases when there are changes in GHA-related paths.

on:
  push:
    branches:
      - master
      - jdk*
      # FOR TESTING: REMOVE THE FOLLOWING LINE BEFORE THE INTEGRATION
      - JDK-8343546-gha-master-cache
    paths:
      - '.github/**'
      - make/conf/github-actions.conf
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-cache
  cancel-in-progress: true

jobs:
  dry-run:
    name: dry-run
    uses: ./.github/workflows/main.yml
    with:
      dry-run: true
